//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /tmp/Tapl.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class TaplLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, ZERO=3, SUCC=4, PRED=5, ISZERO=6, TRUE=7, FALSE=8, IF=9, 
		THEN=10, ELSE=11, WS=12;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "ZERO", "SUCC", "PRED", "ISZERO", "TRUE", "FALSE", "IF", 
		"THEN", "ELSE", "WS"
	};


	public TaplLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public TaplLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'0'", "'succ'", "'pred'", "'iszero'", "'true'", "'false'", 
		"'if'", "'then'", "'else'", "' '"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, "ZERO", "SUCC", "PRED", "ISZERO", "TRUE", "FALSE", "IF", 
		"THEN", "ELSE", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Tapl.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static TaplLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,12,76,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,1,0,1,0,1,1,1,1,1,2,1,2,1,
		3,1,3,1,3,1,3,1,3,1,4,1,4,1,4,1,4,1,4,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,6,
		1,6,1,6,1,6,1,6,1,7,1,7,1,7,1,7,1,7,1,7,1,8,1,8,1,8,1,9,1,9,1,9,1,9,1,
		9,1,10,1,10,1,10,1,10,1,10,1,11,1,11,1,11,1,11,0,0,12,1,1,3,2,5,3,7,4,
		9,5,11,6,13,7,15,8,17,9,19,10,21,11,23,12,1,0,0,75,0,1,1,0,0,0,0,3,1,0,
		0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,15,
		1,0,0,0,0,17,1,0,0,0,0,19,1,0,0,0,0,21,1,0,0,0,0,23,1,0,0,0,1,25,1,0,0,
		0,3,27,1,0,0,0,5,29,1,0,0,0,7,31,1,0,0,0,9,36,1,0,0,0,11,41,1,0,0,0,13,
		48,1,0,0,0,15,53,1,0,0,0,17,59,1,0,0,0,19,62,1,0,0,0,21,67,1,0,0,0,23,
		72,1,0,0,0,25,26,5,40,0,0,26,2,1,0,0,0,27,28,5,41,0,0,28,4,1,0,0,0,29,
		30,5,48,0,0,30,6,1,0,0,0,31,32,5,115,0,0,32,33,5,117,0,0,33,34,5,99,0,
		0,34,35,5,99,0,0,35,8,1,0,0,0,36,37,5,112,0,0,37,38,5,114,0,0,38,39,5,
		101,0,0,39,40,5,100,0,0,40,10,1,0,0,0,41,42,5,105,0,0,42,43,5,115,0,0,
		43,44,5,122,0,0,44,45,5,101,0,0,45,46,5,114,0,0,46,47,5,111,0,0,47,12,
		1,0,0,0,48,49,5,116,0,0,49,50,5,114,0,0,50,51,5,117,0,0,51,52,5,101,0,
		0,52,14,1,0,0,0,53,54,5,102,0,0,54,55,5,97,0,0,55,56,5,108,0,0,56,57,5,
		115,0,0,57,58,5,101,0,0,58,16,1,0,0,0,59,60,5,105,0,0,60,61,5,102,0,0,
		61,18,1,0,0,0,62,63,5,116,0,0,63,64,5,104,0,0,64,65,5,101,0,0,65,66,5,
		110,0,0,66,20,1,0,0,0,67,68,5,101,0,0,68,69,5,108,0,0,69,70,5,115,0,0,
		70,71,5,101,0,0,71,22,1,0,0,0,72,73,5,32,0,0,73,74,1,0,0,0,74,75,6,11,
		0,0,75,24,1,0,0,0,1,0,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
