//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Tapl.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class TaplLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, BIND=3, VAR=4, LAMBDA=5, DOT=6;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "BIND", "VAR", "LAMBDA", "DOT"
	};


	public TaplLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public TaplLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'BIND'", null, "'\\'", "'.'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, "BIND", "VAR", "LAMBDA", "DOT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Tapl.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static TaplLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\b', '\x1E', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x2', '\x2', '\b', 
		'\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', 
		'\b', '\x3', '\x2', '\x3', '\x3', '\x2', '\x63', '|', '\x2', '\x1D', '\x2', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '\xF', '\x3', '\x2', '\x2', '\x2', '\x5', 
		'\x11', '\x3', '\x2', '\x2', '\x2', '\a', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\t', '\x18', '\x3', '\x2', '\x2', '\x2', '\v', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', '\r', '\x1C', '\x3', '\x2', '\x2', '\x2', '\xF', 
		'\x10', '\a', '*', '\x2', '\x2', '\x10', '\x4', '\x3', '\x2', '\x2', '\x2', 
		'\x11', '\x12', '\a', '+', '\x2', '\x2', '\x12', '\x6', '\x3', '\x2', 
		'\x2', '\x2', '\x13', '\x14', '\a', '\x44', '\x2', '\x2', '\x14', '\x15', 
		'\a', 'K', '\x2', '\x2', '\x15', '\x16', '\a', 'P', '\x2', '\x2', '\x16', 
		'\x17', '\a', '\x46', '\x2', '\x2', '\x17', '\b', '\x3', '\x2', '\x2', 
		'\x2', '\x18', '\x19', '\t', '\x2', '\x2', '\x2', '\x19', '\n', '\x3', 
		'\x2', '\x2', '\x2', '\x1A', '\x1B', '\a', '^', '\x2', '\x2', '\x1B', 
		'\f', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x1D', '\a', '\x30', '\x2', 
		'\x2', '\x1D', '\xE', '\x3', '\x2', '\x2', '\x2', '\x3', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
