//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /tmp/FullRecon.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FullReconParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IFullReconVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FullReconParser.toplevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToplevel([NotNull] FullReconParser.ToplevelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>command_term</c>
	/// labeled alternative in <see cref="FullReconParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand_term([NotNull] FullReconParser.Command_termContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>command_binder</c>
	/// labeled alternative in <see cref="FullReconParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand_binder([NotNull] FullReconParser.Command_binderContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binder_type</c>
	/// labeled alternative in <see cref="FullReconParser.binder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinder_type([NotNull] FullReconParser.Binder_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>type_arrowtype</c>
	/// labeled alternative in <see cref="FullReconParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_arrowtype([NotNull] FullReconParser.Type_arrowtypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_type</c>
	/// labeled alternative in <see cref="FullReconParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_type([NotNull] FullReconParser.At_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_ucid</c>
	/// labeled alternative in <see cref="FullReconParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_ucid([NotNull] FullReconParser.At_ucidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_bool</c>
	/// labeled alternative in <see cref="FullReconParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_bool([NotNull] FullReconParser.At_boolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_nat</c>
	/// labeled alternative in <see cref="FullReconParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_nat([NotNull] FullReconParser.At_natContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arrowtype_arrow</c>
	/// labeled alternative in <see cref="FullReconParser.arrowtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrowtype_arrow([NotNull] FullReconParser.Arrowtype_arrowContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arrowtype_atype</c>
	/// labeled alternative in <see cref="FullReconParser.arrowtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrowtype_atype([NotNull] FullReconParser.Arrowtype_atypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_appterm</c>
	/// labeled alternative in <see cref="FullReconParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_appterm([NotNull] FullReconParser.Term_apptermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_ift</c>
	/// labeled alternative in <see cref="FullReconParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_ift([NotNull] FullReconParser.Term_iftContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_ll</c>
	/// labeled alternative in <see cref="FullReconParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_ll([NotNull] FullReconParser.Term_llContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_lu</c>
	/// labeled alternative in <see cref="FullReconParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_lu([NotNull] FullReconParser.Term_luContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_lambda_untyped</c>
	/// labeled alternative in <see cref="FullReconParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_lambda_untyped([NotNull] FullReconParser.Term_lambda_untypedContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_lambda_typed</c>
	/// labeled alternative in <see cref="FullReconParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_lambda_typed([NotNull] FullReconParser.Term_lambda_typedContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_lambda_uscore</c>
	/// labeled alternative in <see cref="FullReconParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_lambda_uscore([NotNull] FullReconParser.Term_lambda_uscoreContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_aterm</c>
	/// labeled alternative in <see cref="FullReconParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_aterm([NotNull] FullReconParser.Appterm_atermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_app</c>
	/// labeled alternative in <see cref="FullReconParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_app([NotNull] FullReconParser.Appterm_appContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_iszero</c>
	/// labeled alternative in <see cref="FullReconParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_iszero([NotNull] FullReconParser.Appterm_iszeroContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_succ</c>
	/// labeled alternative in <see cref="FullReconParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_succ([NotNull] FullReconParser.Appterm_succContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_pred</c>
	/// labeled alternative in <see cref="FullReconParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_pred([NotNull] FullReconParser.Appterm_predContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_paren</c>
	/// labeled alternative in <see cref="FullReconParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_paren([NotNull] FullReconParser.Aterm_parenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_lcid</c>
	/// labeled alternative in <see cref="FullReconParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_lcid([NotNull] FullReconParser.Aterm_lcidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_true</c>
	/// labeled alternative in <see cref="FullReconParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_true([NotNull] FullReconParser.Aterm_trueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_false</c>
	/// labeled alternative in <see cref="FullReconParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_false([NotNull] FullReconParser.Aterm_falseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_intv</c>
	/// labeled alternative in <see cref="FullReconParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_intv([NotNull] FullReconParser.Aterm_intvContext context);
}
