//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /tmp/FullPoly.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FullPolyParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IFullPolyVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FullPolyParser.toplevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToplevel([NotNull] FullPolyParser.ToplevelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>command_term</c>
	/// labeled alternative in <see cref="FullPolyParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand_term([NotNull] FullPolyParser.Command_termContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>command_import</c>
	/// labeled alternative in <see cref="FullPolyParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand_import([NotNull] FullPolyParser.Command_importContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>command_tybinder</c>
	/// labeled alternative in <see cref="FullPolyParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand_tybinder([NotNull] FullPolyParser.Command_tybinderContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>command_binder</c>
	/// labeled alternative in <see cref="FullPolyParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand_binder([NotNull] FullPolyParser.Command_binderContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>command_somebind</c>
	/// labeled alternative in <see cref="FullPolyParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand_somebind([NotNull] FullPolyParser.Command_somebindContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binder_type</c>
	/// labeled alternative in <see cref="FullPolyParser.binder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinder_type([NotNull] FullPolyParser.Binder_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binder_term</c>
	/// labeled alternative in <see cref="FullPolyParser.binder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinder_term([NotNull] FullPolyParser.Binder_termContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>type_arrowtype</c>
	/// labeled alternative in <see cref="FullPolyParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_arrowtype([NotNull] FullPolyParser.Type_arrowtypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>type_all</c>
	/// labeled alternative in <see cref="FullPolyParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_all([NotNull] FullPolyParser.Type_allContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_type</c>
	/// labeled alternative in <see cref="FullPolyParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_type([NotNull] FullPolyParser.At_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_ucid</c>
	/// labeled alternative in <see cref="FullPolyParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_ucid([NotNull] FullPolyParser.At_ucidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_bool</c>
	/// labeled alternative in <see cref="FullPolyParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_bool([NotNull] FullPolyParser.At_boolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_variant</c>
	/// labeled alternative in <see cref="FullPolyParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_variant([NotNull] FullPolyParser.At_variantContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_some</c>
	/// labeled alternative in <see cref="FullPolyParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_some([NotNull] FullPolyParser.At_someContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_ustring</c>
	/// labeled alternative in <see cref="FullPolyParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_ustring([NotNull] FullPolyParser.At_ustringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_uunit</c>
	/// labeled alternative in <see cref="FullPolyParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_uunit([NotNull] FullPolyParser.At_uunitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_record</c>
	/// labeled alternative in <see cref="FullPolyParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_record([NotNull] FullPolyParser.At_recordContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_ufloat</c>
	/// labeled alternative in <see cref="FullPolyParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_ufloat([NotNull] FullPolyParser.At_ufloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_nat</c>
	/// labeled alternative in <see cref="FullPolyParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_nat([NotNull] FullPolyParser.At_natContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>tybinder_type</c>
	/// labeled alternative in <see cref="FullPolyParser.tybinder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTybinder_type([NotNull] FullPolyParser.Tybinder_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>tybinder_empty</c>
	/// labeled alternative in <see cref="FullPolyParser.tybinder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTybinder_empty([NotNull] FullPolyParser.Tybinder_emptyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>fieldtypes_nefieldtypes</c>
	/// labeled alternative in <see cref="FullPolyParser.fieldtypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldtypes_nefieldtypes([NotNull] FullPolyParser.Fieldtypes_nefieldtypesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nefieldtypes_fieldtype</c>
	/// labeled alternative in <see cref="FullPolyParser.nefieldtypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNefieldtypes_fieldtype([NotNull] FullPolyParser.Nefieldtypes_fieldtypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nefieldtypes_nefieldtype</c>
	/// labeled alternative in <see cref="FullPolyParser.nefieldtypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNefieldtypes_nefieldtype([NotNull] FullPolyParser.Nefieldtypes_nefieldtypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>fieldtype_lcid</c>
	/// labeled alternative in <see cref="FullPolyParser.fieldtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldtype_lcid([NotNull] FullPolyParser.Fieldtype_lcidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>fieldtype_type</c>
	/// labeled alternative in <see cref="FullPolyParser.fieldtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldtype_type([NotNull] FullPolyParser.Fieldtype_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arrowtype_arrow</c>
	/// labeled alternative in <see cref="FullPolyParser.arrowtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrowtype_arrow([NotNull] FullPolyParser.Arrowtype_arrowContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arrowtype_atype</c>
	/// labeled alternative in <see cref="FullPolyParser.arrowtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrowtype_atype([NotNull] FullPolyParser.Arrowtype_atypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_appterm</c>
	/// labeled alternative in <see cref="FullPolyParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_appterm([NotNull] FullPolyParser.Term_apptermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_ift</c>
	/// labeled alternative in <see cref="FullPolyParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_ift([NotNull] FullPolyParser.Term_iftContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_caseOf</c>
	/// labeled alternative in <see cref="FullPolyParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_caseOf([NotNull] FullPolyParser.Term_caseOfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_llcid</c>
	/// labeled alternative in <see cref="FullPolyParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_llcid([NotNull] FullPolyParser.Term_llcidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_luc</c>
	/// labeled alternative in <see cref="FullPolyParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_luc([NotNull] FullPolyParser.Term_lucContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_tlambda</c>
	/// labeled alternative in <see cref="FullPolyParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_tlambda([NotNull] FullPolyParser.Term_tlambdaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_ll</c>
	/// labeled alternative in <see cref="FullPolyParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_ll([NotNull] FullPolyParser.Term_llContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_lu</c>
	/// labeled alternative in <see cref="FullPolyParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_lu([NotNull] FullPolyParser.Term_luContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_unpack</c>
	/// labeled alternative in <see cref="FullPolyParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_unpack([NotNull] FullPolyParser.Term_unpackContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_letrec</c>
	/// labeled alternative in <see cref="FullPolyParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_letrec([NotNull] FullPolyParser.Term_letrecContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_tapp</c>
	/// labeled alternative in <see cref="FullPolyParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_tapp([NotNull] FullPolyParser.Appterm_tappContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_times</c>
	/// labeled alternative in <see cref="FullPolyParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_times([NotNull] FullPolyParser.Appterm_timesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_iszero</c>
	/// labeled alternative in <see cref="FullPolyParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_iszero([NotNull] FullPolyParser.Appterm_iszeroContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_path</c>
	/// labeled alternative in <see cref="FullPolyParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_path([NotNull] FullPolyParser.Appterm_pathContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_app_path</c>
	/// labeled alternative in <see cref="FullPolyParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_app_path([NotNull] FullPolyParser.Appterm_app_pathContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_succ</c>
	/// labeled alternative in <see cref="FullPolyParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_succ([NotNull] FullPolyParser.Appterm_succContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_pred</c>
	/// labeled alternative in <see cref="FullPolyParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_pred([NotNull] FullPolyParser.Appterm_predContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_fix</c>
	/// labeled alternative in <see cref="FullPolyParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_fix([NotNull] FullPolyParser.Appterm_fixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ascribeterm_aaa</c>
	/// labeled alternative in <see cref="FullPolyParser.ascribeterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAscribeterm_aaa([NotNull] FullPolyParser.Ascribeterm_aaaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ascribeterm_a</c>
	/// labeled alternative in <see cref="FullPolyParser.ascribeterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAscribeterm_a([NotNull] FullPolyParser.Ascribeterm_aContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pathterm_intv</c>
	/// labeled alternative in <see cref="FullPolyParser.pathterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPathterm_intv([NotNull] FullPolyParser.Pathterm_intvContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pathterm_lcid</c>
	/// labeled alternative in <see cref="FullPolyParser.pathterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPathterm_lcid([NotNull] FullPolyParser.Pathterm_lcidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pathterm_asterm</c>
	/// labeled alternative in <see cref="FullPolyParser.pathterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPathterm_asterm([NotNull] FullPolyParser.Pathterm_astermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>termseq_term</c>
	/// labeled alternative in <see cref="FullPolyParser.termseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermseq_term([NotNull] FullPolyParser.Termseq_termContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>termseq_termseq</c>
	/// labeled alternative in <see cref="FullPolyParser.termseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermseq_termseq([NotNull] FullPolyParser.Termseq_termseqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_paren</c>
	/// labeled alternative in <see cref="FullPolyParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_paren([NotNull] FullPolyParser.Aterm_parenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_inert</c>
	/// labeled alternative in <see cref="FullPolyParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_inert([NotNull] FullPolyParser.Aterm_inertContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_true</c>
	/// labeled alternative in <see cref="FullPolyParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_true([NotNull] FullPolyParser.Aterm_trueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_false</c>
	/// labeled alternative in <see cref="FullPolyParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_false([NotNull] FullPolyParser.Aterm_falseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_lt</c>
	/// labeled alternative in <see cref="FullPolyParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_lt([NotNull] FullPolyParser.Aterm_ltContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_pack</c>
	/// labeled alternative in <see cref="FullPolyParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_pack([NotNull] FullPolyParser.Aterm_packContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_lcid</c>
	/// labeled alternative in <see cref="FullPolyParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_lcid([NotNull] FullPolyParser.Aterm_lcidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_stringv</c>
	/// labeled alternative in <see cref="FullPolyParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_stringv([NotNull] FullPolyParser.Aterm_stringvContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_unit</c>
	/// labeled alternative in <see cref="FullPolyParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_unit([NotNull] FullPolyParser.Aterm_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_fields</c>
	/// labeled alternative in <see cref="FullPolyParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_fields([NotNull] FullPolyParser.Aterm_fieldsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_floatv</c>
	/// labeled alternative in <see cref="FullPolyParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_floatv([NotNull] FullPolyParser.Aterm_floatvContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_intv</c>
	/// labeled alternative in <see cref="FullPolyParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_intv([NotNull] FullPolyParser.Aterm_intvContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>cases_case</c>
	/// labeled alternative in <see cref="FullPolyParser.cases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCases_case([NotNull] FullPolyParser.Cases_caseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>cases_case_vbar_cases</c>
	/// labeled alternative in <see cref="FullPolyParser.cases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCases_case_vbar_cases([NotNull] FullPolyParser.Cases_case_vbar_casesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FullPolyParser.case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase([NotNull] FullPolyParser.CaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FullPolyParser.fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFields([NotNull] FullPolyParser.FieldsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nefields_field</c>
	/// labeled alternative in <see cref="FullPolyParser.nefields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNefields_field([NotNull] FullPolyParser.Nefields_fieldContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nefields_field_comma_nefields</c>
	/// labeled alternative in <see cref="FullPolyParser.nefields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNefields_field_comma_nefields([NotNull] FullPolyParser.Nefields_field_comma_nefieldsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>field_lcid</c>
	/// labeled alternative in <see cref="FullPolyParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField_lcid([NotNull] FullPolyParser.Field_lcidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>field_term</c>
	/// labeled alternative in <see cref="FullPolyParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField_term([NotNull] FullPolyParser.Field_termContext context);
}
