//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /tmp/FullUntyped.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IFullUntypedVisitor{Result}"/>,
/// which can be extended to create a visitor which only needs to handle a subset
/// of the available methods.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class FullUntypedBaseVisitor<Result> : AbstractParseTreeVisitor<Result>, IFullUntypedVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FullUntypedParser.toplevel"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitToplevel([NotNull] FullUntypedParser.ToplevelContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>command_term</c>
	/// labeled alternative in <see cref="FullUntypedParser.command"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitCommand_term([NotNull] FullUntypedParser.Command_termContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>command_tybinder</c>
	/// labeled alternative in <see cref="FullUntypedParser.command"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitCommand_tybinder([NotNull] FullUntypedParser.Command_tybinderContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>command_binder</c>
	/// labeled alternative in <see cref="FullUntypedParser.command"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitCommand_binder([NotNull] FullUntypedParser.Command_binderContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>binder_type</c>
	/// labeled alternative in <see cref="FullUntypedParser.binder"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitBinder_type([NotNull] FullUntypedParser.Binder_typeContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>binder_term</c>
	/// labeled alternative in <see cref="FullUntypedParser.binder"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitBinder_term([NotNull] FullUntypedParser.Binder_termContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>type_arrowtype</c>
	/// labeled alternative in <see cref="FullUntypedParser.type"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitType_arrowtype([NotNull] FullUntypedParser.Type_arrowtypeContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>at_type</c>
	/// labeled alternative in <see cref="FullUntypedParser.atype"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAt_type([NotNull] FullUntypedParser.At_typeContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>at_ucid</c>
	/// labeled alternative in <see cref="FullUntypedParser.atype"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAt_ucid([NotNull] FullUntypedParser.At_ucidContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>at_bool</c>
	/// labeled alternative in <see cref="FullUntypedParser.atype"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAt_bool([NotNull] FullUntypedParser.At_boolContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>at_variant</c>
	/// labeled alternative in <see cref="FullUntypedParser.atype"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAt_variant([NotNull] FullUntypedParser.At_variantContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>at_ustring</c>
	/// labeled alternative in <see cref="FullUntypedParser.atype"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAt_ustring([NotNull] FullUntypedParser.At_ustringContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>at_uunit</c>
	/// labeled alternative in <see cref="FullUntypedParser.atype"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAt_uunit([NotNull] FullUntypedParser.At_uunitContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>at_record</c>
	/// labeled alternative in <see cref="FullUntypedParser.atype"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAt_record([NotNull] FullUntypedParser.At_recordContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>at_ufloat</c>
	/// labeled alternative in <see cref="FullUntypedParser.atype"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAt_ufloat([NotNull] FullUntypedParser.At_ufloatContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>at_nat</c>
	/// labeled alternative in <see cref="FullUntypedParser.atype"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAt_nat([NotNull] FullUntypedParser.At_natContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>tybinder_type</c>
	/// labeled alternative in <see cref="FullUntypedParser.tybinder"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitTybinder_type([NotNull] FullUntypedParser.Tybinder_typeContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>fieldtypes_nefieldtypes</c>
	/// labeled alternative in <see cref="FullUntypedParser.fieldtypes"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitFieldtypes_nefieldtypes([NotNull] FullUntypedParser.Fieldtypes_nefieldtypesContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>nefieldtypes_fieldtype</c>
	/// labeled alternative in <see cref="FullUntypedParser.nefieldtypes"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitNefieldtypes_fieldtype([NotNull] FullUntypedParser.Nefieldtypes_fieldtypeContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>nefieldtypes_nefieldtype</c>
	/// labeled alternative in <see cref="FullUntypedParser.nefieldtypes"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitNefieldtypes_nefieldtype([NotNull] FullUntypedParser.Nefieldtypes_nefieldtypeContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>fieldtype_lcid</c>
	/// labeled alternative in <see cref="FullUntypedParser.fieldtype"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitFieldtype_lcid([NotNull] FullUntypedParser.Fieldtype_lcidContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>fieldtype_type</c>
	/// labeled alternative in <see cref="FullUntypedParser.fieldtype"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitFieldtype_type([NotNull] FullUntypedParser.Fieldtype_typeContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>arrowtype_arrow</c>
	/// labeled alternative in <see cref="FullUntypedParser.arrowtype"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitArrowtype_arrow([NotNull] FullUntypedParser.Arrowtype_arrowContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>arrowtype_atype</c>
	/// labeled alternative in <see cref="FullUntypedParser.arrowtype"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitArrowtype_atype([NotNull] FullUntypedParser.Arrowtype_atypeContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>term_appterm</c>
	/// labeled alternative in <see cref="FullUntypedParser.term"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitTerm_appterm([NotNull] FullUntypedParser.Term_apptermContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>term_ift</c>
	/// labeled alternative in <see cref="FullUntypedParser.term"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitTerm_ift([NotNull] FullUntypedParser.Term_iftContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>term_caseOf</c>
	/// labeled alternative in <see cref="FullUntypedParser.term"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitTerm_caseOf([NotNull] FullUntypedParser.Term_caseOfContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>term_llcid</c>
	/// labeled alternative in <see cref="FullUntypedParser.term"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitTerm_llcid([NotNull] FullUntypedParser.Term_llcidContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>term_luc</c>
	/// labeled alternative in <see cref="FullUntypedParser.term"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitTerm_luc([NotNull] FullUntypedParser.Term_lucContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>term_ll</c>
	/// labeled alternative in <see cref="FullUntypedParser.term"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitTerm_ll([NotNull] FullUntypedParser.Term_llContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>term_lu</c>
	/// labeled alternative in <see cref="FullUntypedParser.term"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitTerm_lu([NotNull] FullUntypedParser.Term_luContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>term_letrec</c>
	/// labeled alternative in <see cref="FullUntypedParser.term"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitTerm_letrec([NotNull] FullUntypedParser.Term_letrecContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_times</c>
	/// labeled alternative in <see cref="FullUntypedParser.appterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAppterm_times([NotNull] FullUntypedParser.Appterm_timesContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_iszero</c>
	/// labeled alternative in <see cref="FullUntypedParser.appterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAppterm_iszero([NotNull] FullUntypedParser.Appterm_iszeroContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_path</c>
	/// labeled alternative in <see cref="FullUntypedParser.appterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAppterm_path([NotNull] FullUntypedParser.Appterm_pathContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_app_path</c>
	/// labeled alternative in <see cref="FullUntypedParser.appterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAppterm_app_path([NotNull] FullUntypedParser.Appterm_app_pathContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_succ</c>
	/// labeled alternative in <see cref="FullUntypedParser.appterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAppterm_succ([NotNull] FullUntypedParser.Appterm_succContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_pred</c>
	/// labeled alternative in <see cref="FullUntypedParser.appterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAppterm_pred([NotNull] FullUntypedParser.Appterm_predContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_fix</c>
	/// labeled alternative in <see cref="FullUntypedParser.appterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAppterm_fix([NotNull] FullUntypedParser.Appterm_fixContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>ascribeterm_aaa</c>
	/// labeled alternative in <see cref="FullUntypedParser.ascribeterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAscribeterm_aaa([NotNull] FullUntypedParser.Ascribeterm_aaaContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>ascribeterm_a</c>
	/// labeled alternative in <see cref="FullUntypedParser.ascribeterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAscribeterm_a([NotNull] FullUntypedParser.Ascribeterm_aContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>pathterm_intv</c>
	/// labeled alternative in <see cref="FullUntypedParser.pathterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitPathterm_intv([NotNull] FullUntypedParser.Pathterm_intvContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>pathterm_lcid</c>
	/// labeled alternative in <see cref="FullUntypedParser.pathterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitPathterm_lcid([NotNull] FullUntypedParser.Pathterm_lcidContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>pathterm_asterm</c>
	/// labeled alternative in <see cref="FullUntypedParser.pathterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitPathterm_asterm([NotNull] FullUntypedParser.Pathterm_astermContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>termseq_term</c>
	/// labeled alternative in <see cref="FullUntypedParser.termseq"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitTermseq_term([NotNull] FullUntypedParser.Termseq_termContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>termseq_termseq</c>
	/// labeled alternative in <see cref="FullUntypedParser.termseq"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitTermseq_termseq([NotNull] FullUntypedParser.Termseq_termseqContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_paren</c>
	/// labeled alternative in <see cref="FullUntypedParser.aterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAterm_paren([NotNull] FullUntypedParser.Aterm_parenContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_inert</c>
	/// labeled alternative in <see cref="FullUntypedParser.aterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAterm_inert([NotNull] FullUntypedParser.Aterm_inertContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_true</c>
	/// labeled alternative in <see cref="FullUntypedParser.aterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAterm_true([NotNull] FullUntypedParser.Aterm_trueContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_false</c>
	/// labeled alternative in <see cref="FullUntypedParser.aterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAterm_false([NotNull] FullUntypedParser.Aterm_falseContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_lt</c>
	/// labeled alternative in <see cref="FullUntypedParser.aterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAterm_lt([NotNull] FullUntypedParser.Aterm_ltContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_lcid</c>
	/// labeled alternative in <see cref="FullUntypedParser.aterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAterm_lcid([NotNull] FullUntypedParser.Aterm_lcidContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_stringv</c>
	/// labeled alternative in <see cref="FullUntypedParser.aterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAterm_stringv([NotNull] FullUntypedParser.Aterm_stringvContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_unit</c>
	/// labeled alternative in <see cref="FullUntypedParser.aterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAterm_unit([NotNull] FullUntypedParser.Aterm_unitContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_fields</c>
	/// labeled alternative in <see cref="FullUntypedParser.aterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAterm_fields([NotNull] FullUntypedParser.Aterm_fieldsContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_floatv</c>
	/// labeled alternative in <see cref="FullUntypedParser.aterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAterm_floatv([NotNull] FullUntypedParser.Aterm_floatvContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_intv</c>
	/// labeled alternative in <see cref="FullUntypedParser.aterm"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitAterm_intv([NotNull] FullUntypedParser.Aterm_intvContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>cases_case</c>
	/// labeled alternative in <see cref="FullUntypedParser.cases"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitCases_case([NotNull] FullUntypedParser.Cases_caseContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>cases_case_vbar_cases</c>
	/// labeled alternative in <see cref="FullUntypedParser.cases"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitCases_case_vbar_cases([NotNull] FullUntypedParser.Cases_case_vbar_casesContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by <see cref="FullUntypedParser.case"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitCase([NotNull] FullUntypedParser.CaseContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by <see cref="FullUntypedParser.fields"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitFields([NotNull] FullUntypedParser.FieldsContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>nefields_field</c>
	/// labeled alternative in <see cref="FullUntypedParser.nefields"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitNefields_field([NotNull] FullUntypedParser.Nefields_fieldContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>nefields_field_comma_nefields</c>
	/// labeled alternative in <see cref="FullUntypedParser.nefields"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitNefields_field_comma_nefields([NotNull] FullUntypedParser.Nefields_field_comma_nefieldsContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>field_lcid</c>
	/// labeled alternative in <see cref="FullUntypedParser.field"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitField_lcid([NotNull] FullUntypedParser.Field_lcidContext context) { return VisitChildren(context); }
	/// <summary>
	/// Visit a parse tree produced by the <c>field_term</c>
	/// labeled alternative in <see cref="FullUntypedParser.field"/>.
	/// <para>
	/// The default implementation returns the result of calling <see cref="AbstractParseTreeVisitor{Result}.VisitChildren(IRuleNode)"/>
	/// on <paramref name="context"/>.
	/// </para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	public virtual Result VisitField_term([NotNull] FullUntypedParser.Field_termContext context) { return VisitChildren(context); }
}
