//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /tmp/FullUntyped.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class FullUntypedParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		TYPE=1, INERT=2, IF=3, THEN=4, ELSE=5, TRUE=6, FALSE=7, BOOL=8, CASE=9, 
		OF=10, AS=11, LAMBDA=12, LET=13, IN=14, FIX=15, LETREC=16, USTRING=17, 
		UNIT=18, UUNIT=19, TIMESFLOAT=20, UFLOAT=21, SUCC=22, PRED=23, ISZERO=24, 
		NAT=25, STRINGV=26, USCORE=27, APOSTROPHE=28, DQUOTE=29, BANG=30, HASH=31, 
		TRIANGLE=32, STAR=33, VBAR=34, DOT=35, SEMI=36, COMMA=37, SLASH=38, COLON=39, 
		COLONCOLON=40, EQ=41, EQEQ=42, LSQUARE=43, LT=44, LCURLY=45, LPAREN=46, 
		LEFTARROW=47, LCURLYBAR=48, LSQUAREBAR=49, RCURLY=50, RPAREN=51, RSQUARE=52, 
		GT=53, BARRCURLY=54, BARGT=55, BARRSQUARE=56, COLONEQ=57, ARROW=58, DARROW=59, 
		DDARROW=60, FLOATV=61, INTV=62, UCID=63, LCID=64, WS=65, TAB=66, NL=67, 
		NL1=68;
	public const int
		RULE_toplevel = 0, RULE_command = 1, RULE_binder = 2, RULE_type = 3, RULE_atype = 4, 
		RULE_tybinder = 5, RULE_fieldtypes = 6, RULE_nefieldtypes = 7, RULE_fieldtype = 8, 
		RULE_arrowtype = 9, RULE_term = 10, RULE_appterm = 11, RULE_ascribeterm = 12, 
		RULE_pathterm = 13, RULE_termseq = 14, RULE_aterm = 15, RULE_cases = 16, 
		RULE_case = 17, RULE_fields = 18, RULE_nefields = 19, RULE_field = 20;
	public static readonly string[] ruleNames = {
		"toplevel", "command", "binder", "type", "atype", "tybinder", "fieldtypes", 
		"nefieldtypes", "fieldtype", "arrowtype", "term", "appterm", "ascribeterm", 
		"pathterm", "termseq", "aterm", "cases", "case", "fields", "nefields", 
		"field"
	};

	private static readonly string[] _LiteralNames = {
		null, "'type'", "'inert'", "'if'", "'then'", "'else'", "'true'", "'false'", 
		"'Bool'", "'case'", "'of'", "'as'", "'lambda'", "'let'", "'in'", "'fix'", 
		"'letrec'", "'String'", "'unit'", "'Unit'", "'timesfloat'", "'Float'", 
		"'succ'", "'pred'", "'iszero'", "'Nat'", null, "'_'", "'''", "'\"'", "'!'", 
		"'#'", "'$'", "'*'", "'|'", "'.'", "';'", "','", "'/'", "':'", "'::'", 
		"'='", "'=='", "'['", "'<'", "'{'", "'('", "'<-'", "'{|'", "'[|'", "'}'", 
		"')'", "']'", "'>'", "'|}'", "'|>'", "'|]'", "':='", "'->'", "'=>'", "'==>'", 
		null, null, null, null, "' '", "'\\t'", "'\\r'", "'\\n'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "TYPE", "INERT", "IF", "THEN", "ELSE", "TRUE", "FALSE", "BOOL", 
		"CASE", "OF", "AS", "LAMBDA", "LET", "IN", "FIX", "LETREC", "USTRING", 
		"UNIT", "UUNIT", "TIMESFLOAT", "UFLOAT", "SUCC", "PRED", "ISZERO", "NAT", 
		"STRINGV", "USCORE", "APOSTROPHE", "DQUOTE", "BANG", "HASH", "TRIANGLE", 
		"STAR", "VBAR", "DOT", "SEMI", "COMMA", "SLASH", "COLON", "COLONCOLON", 
		"EQ", "EQEQ", "LSQUARE", "LT", "LCURLY", "LPAREN", "LEFTARROW", "LCURLYBAR", 
		"LSQUAREBAR", "RCURLY", "RPAREN", "RSQUARE", "GT", "BARRCURLY", "BARGT", 
		"BARRSQUARE", "COLONEQ", "ARROW", "DARROW", "DDARROW", "FLOATV", "INTV", 
		"UCID", "LCID", "WS", "TAB", "NL", "NL1"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "FullUntyped.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static FullUntypedParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public FullUntypedParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public FullUntypedParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ToplevelContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public CommandContext command() {
			return GetRuleContext<CommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(FullUntypedParser.SEMI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ToplevelContext toplevel() {
			return GetRuleContext<ToplevelContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(FullUntypedParser.Eof, 0); }
		public ToplevelContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_toplevel; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitToplevel(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ToplevelContext toplevel() {
		ToplevelContext _localctx = new ToplevelContext(Context, State);
		EnterRule(_localctx, 0, RULE_toplevel);
		try {
			State = 47;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INERT:
			case IF:
			case TRUE:
			case FALSE:
			case CASE:
			case LAMBDA:
			case LET:
			case FIX:
			case LETREC:
			case UNIT:
			case TIMESFLOAT:
			case SUCC:
			case PRED:
			case ISZERO:
			case STRINGV:
			case LT:
			case LCURLY:
			case LPAREN:
			case FLOATV:
			case INTV:
			case UCID:
			case LCID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 42;
				command();
				State = 43;
				Match(SEMI);
				State = 44;
				toplevel();
				}
				break;
			case Eof:
				EnterOuterAlt(_localctx, 2);
				{
				State = 46;
				Match(Eof);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommandContext : ParserRuleContext {
		public CommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_command; } }
	 
		public CommandContext() { }
		public virtual void CopyFrom(CommandContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Command_binderContext : CommandContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LCID() { return GetToken(FullUntypedParser.LCID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BinderContext binder() {
			return GetRuleContext<BinderContext>(0);
		}
		public Command_binderContext(CommandContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCommand_binder(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Command_termContext : CommandContext {
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public Command_termContext(CommandContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCommand_term(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Command_tybinderContext : CommandContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UCID() { return GetToken(FullUntypedParser.UCID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TybinderContext tybinder() {
			return GetRuleContext<TybinderContext>(0);
		}
		public Command_tybinderContext(CommandContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCommand_tybinder(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CommandContext command() {
		CommandContext _localctx = new CommandContext(Context, State);
		EnterRule(_localctx, 2, RULE_command);
		try {
			State = 54;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				_localctx = new Command_termContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 49;
				term();
				}
				break;
			case 2:
				_localctx = new Command_tybinderContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 50;
				Match(UCID);
				State = 51;
				tybinder();
				}
				break;
			case 3:
				_localctx = new Command_binderContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 52;
				Match(LCID);
				State = 53;
				binder();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BinderContext : ParserRuleContext {
		public BinderContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_binder; } }
	 
		public BinderContext() { }
		public virtual void CopyFrom(BinderContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Binder_termContext : BinderContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(FullUntypedParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public Binder_termContext(BinderContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinder_term(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Binder_typeContext : BinderContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(FullUntypedParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public Binder_typeContext(BinderContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinder_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BinderContext binder() {
		BinderContext _localctx = new BinderContext(Context, State);
		EnterRule(_localctx, 4, RULE_binder);
		try {
			State = 60;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case COLON:
				_localctx = new Binder_typeContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 56;
				Match(COLON);
				State = 57;
				type();
				}
				break;
			case EQ:
				_localctx = new Binder_termContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 58;
				Match(EQ);
				State = 59;
				term();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContext : ParserRuleContext {
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
	 
		public TypeContext() { }
		public virtual void CopyFrom(TypeContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Type_arrowtypeContext : TypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArrowtypeContext arrowtype() {
			return GetRuleContext<ArrowtypeContext>(0);
		}
		public Type_arrowtypeContext(TypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType_arrowtype(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeContext type() {
		TypeContext _localctx = new TypeContext(Context, State);
		EnterRule(_localctx, 6, RULE_type);
		try {
			_localctx = new Type_arrowtypeContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 62;
			arrowtype();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AtypeContext : ParserRuleContext {
		public AtypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atype; } }
	 
		public AtypeContext() { }
		public virtual void CopyFrom(AtypeContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class At_natContext : AtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAT() { return GetToken(FullUntypedParser.NAT, 0); }
		public At_natContext(AtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAt_nat(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class At_boolContext : AtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOL() { return GetToken(FullUntypedParser.BOOL, 0); }
		public At_boolContext(AtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAt_bool(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class At_recordContext : AtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LCURLY() { return GetToken(FullUntypedParser.LCURLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FieldtypesContext fieldtypes() {
			return GetRuleContext<FieldtypesContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RCURLY() { return GetToken(FullUntypedParser.RCURLY, 0); }
		public At_recordContext(AtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAt_record(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class At_ucidContext : AtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UCID() { return GetToken(FullUntypedParser.UCID, 0); }
		public At_ucidContext(AtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAt_ucid(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class At_uunitContext : AtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UUNIT() { return GetToken(FullUntypedParser.UUNIT, 0); }
		public At_uunitContext(AtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAt_uunit(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class At_typeContext : AtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(FullUntypedParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(FullUntypedParser.RPAREN, 0); }
		public At_typeContext(AtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAt_type(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class At_variantContext : AtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(FullUntypedParser.LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FieldtypesContext fieldtypes() {
			return GetRuleContext<FieldtypesContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(FullUntypedParser.GT, 0); }
		public At_variantContext(AtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAt_variant(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class At_ustringContext : AtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode USTRING() { return GetToken(FullUntypedParser.USTRING, 0); }
		public At_ustringContext(AtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAt_ustring(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class At_ufloatContext : AtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UFLOAT() { return GetToken(FullUntypedParser.UFLOAT, 0); }
		public At_ufloatContext(AtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAt_ufloat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AtypeContext atype() {
		AtypeContext _localctx = new AtypeContext(Context, State);
		EnterRule(_localctx, 8, RULE_atype);
		try {
			State = 82;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LPAREN:
				_localctx = new At_typeContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 64;
				Match(LPAREN);
				State = 65;
				type();
				State = 66;
				Match(RPAREN);
				}
				break;
			case UCID:
				_localctx = new At_ucidContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 68;
				Match(UCID);
				}
				break;
			case BOOL:
				_localctx = new At_boolContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 69;
				Match(BOOL);
				}
				break;
			case LT:
				_localctx = new At_variantContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 70;
				Match(LT);
				State = 71;
				fieldtypes();
				State = 72;
				Match(GT);
				}
				break;
			case USTRING:
				_localctx = new At_ustringContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 74;
				Match(USTRING);
				}
				break;
			case UUNIT:
				_localctx = new At_uunitContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 75;
				Match(UUNIT);
				}
				break;
			case LCURLY:
				_localctx = new At_recordContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 76;
				Match(LCURLY);
				State = 77;
				fieldtypes();
				State = 78;
				Match(RCURLY);
				}
				break;
			case UFLOAT:
				_localctx = new At_ufloatContext(_localctx);
				EnterOuterAlt(_localctx, 8);
				{
				State = 80;
				Match(UFLOAT);
				}
				break;
			case NAT:
				_localctx = new At_natContext(_localctx);
				EnterOuterAlt(_localctx, 9);
				{
				State = 81;
				Match(NAT);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TybinderContext : ParserRuleContext {
		public TybinderContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tybinder; } }
	 
		public TybinderContext() { }
		public virtual void CopyFrom(TybinderContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Tybinder_typeContext : TybinderContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(FullUntypedParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public Tybinder_typeContext(TybinderContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTybinder_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TybinderContext tybinder() {
		TybinderContext _localctx = new TybinderContext(Context, State);
		EnterRule(_localctx, 10, RULE_tybinder);
		try {
			_localctx = new Tybinder_typeContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 84;
			Match(EQ);
			State = 85;
			type();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldtypesContext : ParserRuleContext {
		public FieldtypesContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fieldtypes; } }
	 
		public FieldtypesContext() { }
		public virtual void CopyFrom(FieldtypesContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Fieldtypes_nefieldtypesContext : FieldtypesContext {
		[System.Diagnostics.DebuggerNonUserCode] public NefieldtypesContext nefieldtypes() {
			return GetRuleContext<NefieldtypesContext>(0);
		}
		public Fieldtypes_nefieldtypesContext(FieldtypesContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFieldtypes_nefieldtypes(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FieldtypesContext fieldtypes() {
		FieldtypesContext _localctx = new FieldtypesContext(Context, State);
		EnterRule(_localctx, 12, RULE_fieldtypes);
		try {
			_localctx = new Fieldtypes_nefieldtypesContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 87;
			nefieldtypes();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NefieldtypesContext : ParserRuleContext {
		public NefieldtypesContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nefieldtypes; } }
	 
		public NefieldtypesContext() { }
		public virtual void CopyFrom(NefieldtypesContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Nefieldtypes_fieldtypeContext : NefieldtypesContext {
		[System.Diagnostics.DebuggerNonUserCode] public FieldtypeContext fieldtype() {
			return GetRuleContext<FieldtypeContext>(0);
		}
		public Nefieldtypes_fieldtypeContext(NefieldtypesContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNefieldtypes_fieldtype(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Nefieldtypes_nefieldtypeContext : NefieldtypesContext {
		[System.Diagnostics.DebuggerNonUserCode] public FieldtypeContext fieldtype() {
			return GetRuleContext<FieldtypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA() { return GetToken(FullUntypedParser.COMMA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NefieldtypesContext nefieldtypes() {
			return GetRuleContext<NefieldtypesContext>(0);
		}
		public Nefieldtypes_nefieldtypeContext(NefieldtypesContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNefieldtypes_nefieldtype(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NefieldtypesContext nefieldtypes() {
		NefieldtypesContext _localctx = new NefieldtypesContext(Context, State);
		EnterRule(_localctx, 14, RULE_nefieldtypes);
		try {
			State = 94;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				_localctx = new Nefieldtypes_fieldtypeContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 89;
				fieldtype();
				}
				break;
			case 2:
				_localctx = new Nefieldtypes_nefieldtypeContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 90;
				fieldtype();
				State = 91;
				Match(COMMA);
				State = 92;
				nefieldtypes();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldtypeContext : ParserRuleContext {
		public FieldtypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fieldtype; } }
	 
		public FieldtypeContext() { }
		public virtual void CopyFrom(FieldtypeContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Fieldtype_lcidContext : FieldtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LCID() { return GetToken(FullUntypedParser.LCID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(FullUntypedParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public Fieldtype_lcidContext(FieldtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFieldtype_lcid(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Fieldtype_typeContext : FieldtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public Fieldtype_typeContext(FieldtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFieldtype_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FieldtypeContext fieldtype() {
		FieldtypeContext _localctx = new FieldtypeContext(Context, State);
		EnterRule(_localctx, 16, RULE_fieldtype);
		try {
			State = 100;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LCID:
				_localctx = new Fieldtype_lcidContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 96;
				Match(LCID);
				State = 97;
				Match(COLON);
				State = 98;
				type();
				}
				break;
			case BOOL:
			case USTRING:
			case UUNIT:
			case UFLOAT:
			case NAT:
			case LT:
			case LCURLY:
			case LPAREN:
			case UCID:
				_localctx = new Fieldtype_typeContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 99;
				type();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrowtypeContext : ParserRuleContext {
		public ArrowtypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arrowtype; } }
	 
		public ArrowtypeContext() { }
		public virtual void CopyFrom(ArrowtypeContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Arrowtype_atypeContext : ArrowtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public AtypeContext atype() {
			return GetRuleContext<AtypeContext>(0);
		}
		public Arrowtype_atypeContext(ArrowtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrowtype_atype(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Arrowtype_arrowContext : ArrowtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public AtypeContext atype() {
			return GetRuleContext<AtypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ARROW() { return GetToken(FullUntypedParser.ARROW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArrowtypeContext arrowtype() {
			return GetRuleContext<ArrowtypeContext>(0);
		}
		public Arrowtype_arrowContext(ArrowtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrowtype_arrow(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArrowtypeContext arrowtype() {
		ArrowtypeContext _localctx = new ArrowtypeContext(Context, State);
		EnterRule(_localctx, 18, RULE_arrowtype);
		try {
			State = 107;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				_localctx = new Arrowtype_arrowContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 102;
				atype();
				State = 103;
				Match(ARROW);
				State = 104;
				arrowtype();
				}
				break;
			case 2:
				_localctx = new Arrowtype_atypeContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 106;
				atype();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TermContext : ParserRuleContext {
		public TermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_term; } }
	 
		public TermContext() { }
		public virtual void CopyFrom(TermContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Term_lucContext : TermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LAMBDA() { return GetToken(FullUntypedParser.LAMBDA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode USCORE() { return GetToken(FullUntypedParser.USCORE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(FullUntypedParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT() { return GetToken(FullUntypedParser.DOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public Term_lucContext(TermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTerm_luc(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Term_apptermContext : TermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ApptermContext appterm() {
			return GetRuleContext<ApptermContext>(0);
		}
		public Term_apptermContext(TermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTerm_appterm(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Term_iftContext : TermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(FullUntypedParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermContext[] term() {
			return GetRuleContexts<TermContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term(int i) {
			return GetRuleContext<TermContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode THEN() { return GetToken(FullUntypedParser.THEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(FullUntypedParser.ELSE, 0); }
		public Term_iftContext(TermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTerm_ift(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Term_llContext : TermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LET() { return GetToken(FullUntypedParser.LET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LCID() { return GetToken(FullUntypedParser.LCID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(FullUntypedParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermContext[] term() {
			return GetRuleContexts<TermContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term(int i) {
			return GetRuleContext<TermContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IN() { return GetToken(FullUntypedParser.IN, 0); }
		public Term_llContext(TermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTerm_ll(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Term_luContext : TermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LET() { return GetToken(FullUntypedParser.LET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode USCORE() { return GetToken(FullUntypedParser.USCORE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(FullUntypedParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermContext[] term() {
			return GetRuleContexts<TermContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term(int i) {
			return GetRuleContext<TermContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IN() { return GetToken(FullUntypedParser.IN, 0); }
		public Term_luContext(TermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTerm_lu(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Term_caseOfContext : TermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CASE() { return GetToken(FullUntypedParser.CASE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OF() { return GetToken(FullUntypedParser.OF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CasesContext cases() {
			return GetRuleContext<CasesContext>(0);
		}
		public Term_caseOfContext(TermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTerm_caseOf(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Term_letrecContext : TermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LETREC() { return GetToken(FullUntypedParser.LETREC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LCID() { return GetToken(FullUntypedParser.LCID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(FullUntypedParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(FullUntypedParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermContext[] term() {
			return GetRuleContexts<TermContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term(int i) {
			return GetRuleContext<TermContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IN() { return GetToken(FullUntypedParser.IN, 0); }
		public Term_letrecContext(TermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTerm_letrec(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Term_llcidContext : TermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LAMBDA() { return GetToken(FullUntypedParser.LAMBDA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LCID() { return GetToken(FullUntypedParser.LCID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(FullUntypedParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT() { return GetToken(FullUntypedParser.DOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public Term_llcidContext(TermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTerm_llcid(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TermContext term() {
		TermContext _localctx = new TermContext(Context, State);
		EnterRule(_localctx, 20, RULE_term);
		try {
			State = 159;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				_localctx = new Term_apptermContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 109;
				appterm(0);
				}
				break;
			case 2:
				_localctx = new Term_iftContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 110;
				Match(IF);
				State = 111;
				term();
				State = 112;
				Match(THEN);
				State = 113;
				term();
				State = 114;
				Match(ELSE);
				State = 115;
				term();
				}
				break;
			case 3:
				_localctx = new Term_caseOfContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 117;
				Match(CASE);
				State = 118;
				term();
				State = 119;
				Match(OF);
				State = 120;
				cases();
				}
				break;
			case 4:
				_localctx = new Term_llcidContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 122;
				Match(LAMBDA);
				State = 123;
				Match(LCID);
				State = 124;
				Match(COLON);
				State = 125;
				type();
				State = 126;
				Match(DOT);
				State = 127;
				term();
				}
				break;
			case 5:
				_localctx = new Term_lucContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 129;
				Match(LAMBDA);
				State = 130;
				Match(USCORE);
				State = 131;
				Match(COLON);
				State = 132;
				type();
				State = 133;
				Match(DOT);
				State = 134;
				term();
				}
				break;
			case 6:
				_localctx = new Term_llContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 136;
				Match(LET);
				State = 137;
				Match(LCID);
				State = 138;
				Match(EQ);
				State = 139;
				term();
				State = 140;
				Match(IN);
				State = 141;
				term();
				}
				break;
			case 7:
				_localctx = new Term_luContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 143;
				Match(LET);
				State = 144;
				Match(USCORE);
				State = 145;
				Match(EQ);
				State = 146;
				term();
				State = 147;
				Match(IN);
				State = 148;
				term();
				}
				break;
			case 8:
				_localctx = new Term_letrecContext(_localctx);
				EnterOuterAlt(_localctx, 8);
				{
				State = 150;
				Match(LETREC);
				State = 151;
				Match(LCID);
				State = 152;
				Match(COLON);
				State = 153;
				type();
				State = 154;
				Match(EQ);
				State = 155;
				term();
				State = 156;
				Match(IN);
				State = 157;
				term();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ApptermContext : ParserRuleContext {
		public ApptermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_appterm; } }
	 
		public ApptermContext() { }
		public virtual void CopyFrom(ApptermContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Appterm_timesContext : ApptermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TIMESFLOAT() { return GetToken(FullUntypedParser.TIMESFLOAT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PathtermContext[] pathterm() {
			return GetRuleContexts<PathtermContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PathtermContext pathterm(int i) {
			return GetRuleContext<PathtermContext>(i);
		}
		public Appterm_timesContext(ApptermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAppterm_times(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Appterm_iszeroContext : ApptermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ISZERO() { return GetToken(FullUntypedParser.ISZERO, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PathtermContext pathterm() {
			return GetRuleContext<PathtermContext>(0);
		}
		public Appterm_iszeroContext(ApptermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAppterm_iszero(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Appterm_pathContext : ApptermContext {
		[System.Diagnostics.DebuggerNonUserCode] public PathtermContext pathterm() {
			return GetRuleContext<PathtermContext>(0);
		}
		public Appterm_pathContext(ApptermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAppterm_path(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Appterm_app_pathContext : ApptermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ApptermContext appterm() {
			return GetRuleContext<ApptermContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PathtermContext pathterm() {
			return GetRuleContext<PathtermContext>(0);
		}
		public Appterm_app_pathContext(ApptermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAppterm_app_path(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Appterm_succContext : ApptermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SUCC() { return GetToken(FullUntypedParser.SUCC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PathtermContext pathterm() {
			return GetRuleContext<PathtermContext>(0);
		}
		public Appterm_succContext(ApptermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAppterm_succ(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Appterm_predContext : ApptermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PRED() { return GetToken(FullUntypedParser.PRED, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PathtermContext pathterm() {
			return GetRuleContext<PathtermContext>(0);
		}
		public Appterm_predContext(ApptermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAppterm_pred(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Appterm_fixContext : ApptermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FIX() { return GetToken(FullUntypedParser.FIX, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PathtermContext pathterm() {
			return GetRuleContext<PathtermContext>(0);
		}
		public Appterm_fixContext(ApptermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAppterm_fix(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ApptermContext appterm() {
		return appterm(0);
	}

	private ApptermContext appterm(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ApptermContext _localctx = new ApptermContext(Context, _parentState);
		ApptermContext _prevctx = _localctx;
		int _startState = 22;
		EnterRecursionRule(_localctx, 22, RULE_appterm, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 175;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INERT:
			case TRUE:
			case FALSE:
			case UNIT:
			case STRINGV:
			case LT:
			case LCURLY:
			case LPAREN:
			case FLOATV:
			case INTV:
			case LCID:
				{
				_localctx = new Appterm_pathContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 162;
				pathterm(0);
				}
				break;
			case FIX:
				{
				_localctx = new Appterm_fixContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 163;
				Match(FIX);
				State = 164;
				pathterm(0);
				}
				break;
			case TIMESFLOAT:
				{
				_localctx = new Appterm_timesContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 165;
				Match(TIMESFLOAT);
				State = 166;
				pathterm(0);
				State = 167;
				pathterm(0);
				}
				break;
			case SUCC:
				{
				_localctx = new Appterm_succContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 169;
				Match(SUCC);
				State = 170;
				pathterm(0);
				}
				break;
			case PRED:
				{
				_localctx = new Appterm_predContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 171;
				Match(PRED);
				State = 172;
				pathterm(0);
				}
				break;
			case ISZERO:
				{
				_localctx = new Appterm_iszeroContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 173;
				Match(ISZERO);
				State = 174;
				pathterm(0);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 181;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new Appterm_app_pathContext(new ApptermContext(_parentctx, _parentState));
					PushNewRecursionContext(_localctx, _startState, RULE_appterm);
					State = 177;
					if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
					State = 178;
					pathterm(0);
					}
					} 
				}
				State = 183;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class AscribetermContext : ParserRuleContext {
		public AscribetermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ascribeterm; } }
	 
		public AscribetermContext() { }
		public virtual void CopyFrom(AscribetermContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Ascribeterm_aaaContext : AscribetermContext {
		[System.Diagnostics.DebuggerNonUserCode] public AtermContext aterm() {
			return GetRuleContext<AtermContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AS() { return GetToken(FullUntypedParser.AS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public Ascribeterm_aaaContext(AscribetermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAscribeterm_aaa(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Ascribeterm_aContext : AscribetermContext {
		[System.Diagnostics.DebuggerNonUserCode] public AtermContext aterm() {
			return GetRuleContext<AtermContext>(0);
		}
		public Ascribeterm_aContext(AscribetermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAscribeterm_a(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AscribetermContext ascribeterm() {
		AscribetermContext _localctx = new AscribetermContext(Context, State);
		EnterRule(_localctx, 24, RULE_ascribeterm);
		try {
			State = 189;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				_localctx = new Ascribeterm_aaaContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 184;
				aterm();
				State = 185;
				Match(AS);
				State = 186;
				type();
				}
				break;
			case 2:
				_localctx = new Ascribeterm_aContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 188;
				aterm();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PathtermContext : ParserRuleContext {
		public PathtermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pathterm; } }
	 
		public PathtermContext() { }
		public virtual void CopyFrom(PathtermContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Pathterm_intvContext : PathtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public PathtermContext pathterm() {
			return GetRuleContext<PathtermContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT() { return GetToken(FullUntypedParser.DOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTV() { return GetToken(FullUntypedParser.INTV, 0); }
		public Pathterm_intvContext(PathtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPathterm_intv(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Pathterm_lcidContext : PathtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public PathtermContext pathterm() {
			return GetRuleContext<PathtermContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT() { return GetToken(FullUntypedParser.DOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LCID() { return GetToken(FullUntypedParser.LCID, 0); }
		public Pathterm_lcidContext(PathtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPathterm_lcid(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Pathterm_astermContext : PathtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public AscribetermContext ascribeterm() {
			return GetRuleContext<AscribetermContext>(0);
		}
		public Pathterm_astermContext(PathtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPathterm_asterm(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PathtermContext pathterm() {
		return pathterm(0);
	}

	private PathtermContext pathterm(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		PathtermContext _localctx = new PathtermContext(Context, _parentState);
		PathtermContext _prevctx = _localctx;
		int _startState = 26;
		EnterRecursionRule(_localctx, 26, RULE_pathterm, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			_localctx = new Pathterm_astermContext(_localctx);
			Context = _localctx;
			_prevctx = _localctx;

			State = 192;
			ascribeterm();
			}
			Context.Stop = TokenStream.LT(-1);
			State = 202;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 200;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
					case 1:
						{
						_localctx = new Pathterm_lcidContext(new PathtermContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_pathterm);
						State = 194;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 195;
						Match(DOT);
						State = 196;
						Match(LCID);
						}
						break;
					case 2:
						{
						_localctx = new Pathterm_intvContext(new PathtermContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_pathterm);
						State = 197;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 198;
						Match(DOT);
						State = 199;
						Match(INTV);
						}
						break;
					}
					} 
				}
				State = 204;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,12,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class TermseqContext : ParserRuleContext {
		public TermseqContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_termseq; } }
	 
		public TermseqContext() { }
		public virtual void CopyFrom(TermseqContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Termseq_termContext : TermseqContext {
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public Termseq_termContext(TermseqContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTermseq_term(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Termseq_termseqContext : TermseqContext {
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(FullUntypedParser.SEMI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermseqContext termseq() {
			return GetRuleContext<TermseqContext>(0);
		}
		public Termseq_termseqContext(TermseqContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTermseq_termseq(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TermseqContext termseq() {
		TermseqContext _localctx = new TermseqContext(Context, State);
		EnterRule(_localctx, 28, RULE_termseq);
		try {
			State = 210;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				_localctx = new Termseq_termContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 205;
				term();
				}
				break;
			case 2:
				_localctx = new Termseq_termseqContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 206;
				term();
				State = 207;
				Match(SEMI);
				State = 208;
				termseq();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AtermContext : ParserRuleContext {
		public AtermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_aterm; } }
	 
		public AtermContext() { }
		public virtual void CopyFrom(AtermContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Aterm_falseContext : AtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FALSE() { return GetToken(FullUntypedParser.FALSE, 0); }
		public Aterm_falseContext(AtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAterm_false(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Aterm_fieldsContext : AtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LCURLY() { return GetToken(FullUntypedParser.LCURLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FieldsContext fields() {
			return GetRuleContext<FieldsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RCURLY() { return GetToken(FullUntypedParser.RCURLY, 0); }
		public Aterm_fieldsContext(AtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAterm_fields(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Aterm_inertContext : AtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INERT() { return GetToken(FullUntypedParser.INERT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LSQUARE() { return GetToken(FullUntypedParser.LSQUARE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RSQUARE() { return GetToken(FullUntypedParser.RSQUARE, 0); }
		public Aterm_inertContext(AtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAterm_inert(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Aterm_unitContext : AtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UNIT() { return GetToken(FullUntypedParser.UNIT, 0); }
		public Aterm_unitContext(AtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAterm_unit(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Aterm_trueContext : AtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRUE() { return GetToken(FullUntypedParser.TRUE, 0); }
		public Aterm_trueContext(AtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAterm_true(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Aterm_lcidContext : AtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LCID() { return GetToken(FullUntypedParser.LCID, 0); }
		public Aterm_lcidContext(AtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAterm_lcid(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Aterm_intvContext : AtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTV() { return GetToken(FullUntypedParser.INTV, 0); }
		public Aterm_intvContext(AtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAterm_intv(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Aterm_parenContext : AtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(FullUntypedParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermseqContext termseq() {
			return GetRuleContext<TermseqContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(FullUntypedParser.RPAREN, 0); }
		public Aterm_parenContext(AtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAterm_paren(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Aterm_floatvContext : AtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOATV() { return GetToken(FullUntypedParser.FLOATV, 0); }
		public Aterm_floatvContext(AtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAterm_floatv(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Aterm_ltContext : AtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(FullUntypedParser.LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LCID() { return GetToken(FullUntypedParser.LCID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(FullUntypedParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(FullUntypedParser.GT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AS() { return GetToken(FullUntypedParser.AS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public Aterm_ltContext(AtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAterm_lt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Aterm_stringvContext : AtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRINGV() { return GetToken(FullUntypedParser.STRINGV, 0); }
		public Aterm_stringvContext(AtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAterm_stringv(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AtermContext aterm() {
		AtermContext _localctx = new AtermContext(Context, State);
		EnterRule(_localctx, 30, RULE_aterm);
		try {
			State = 240;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LPAREN:
				_localctx = new Aterm_parenContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 212;
				Match(LPAREN);
				State = 213;
				termseq();
				State = 214;
				Match(RPAREN);
				}
				break;
			case INERT:
				_localctx = new Aterm_inertContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 216;
				Match(INERT);
				State = 217;
				Match(LSQUARE);
				State = 218;
				type();
				State = 219;
				Match(RSQUARE);
				}
				break;
			case TRUE:
				_localctx = new Aterm_trueContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 221;
				Match(TRUE);
				}
				break;
			case FALSE:
				_localctx = new Aterm_falseContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 222;
				Match(FALSE);
				}
				break;
			case LT:
				_localctx = new Aterm_ltContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 223;
				Match(LT);
				State = 224;
				Match(LCID);
				State = 225;
				Match(EQ);
				State = 226;
				term();
				State = 227;
				Match(GT);
				State = 228;
				Match(AS);
				State = 229;
				type();
				}
				break;
			case LCID:
				_localctx = new Aterm_lcidContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 231;
				Match(LCID);
				}
				break;
			case STRINGV:
				_localctx = new Aterm_stringvContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 232;
				Match(STRINGV);
				}
				break;
			case UNIT:
				_localctx = new Aterm_unitContext(_localctx);
				EnterOuterAlt(_localctx, 8);
				{
				State = 233;
				Match(UNIT);
				}
				break;
			case LCURLY:
				_localctx = new Aterm_fieldsContext(_localctx);
				EnterOuterAlt(_localctx, 9);
				{
				State = 234;
				Match(LCURLY);
				State = 235;
				fields();
				State = 236;
				Match(RCURLY);
				}
				break;
			case FLOATV:
				_localctx = new Aterm_floatvContext(_localctx);
				EnterOuterAlt(_localctx, 10);
				{
				State = 238;
				Match(FLOATV);
				}
				break;
			case INTV:
				_localctx = new Aterm_intvContext(_localctx);
				EnterOuterAlt(_localctx, 11);
				{
				State = 239;
				Match(INTV);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CasesContext : ParserRuleContext {
		public CasesContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cases; } }
	 
		public CasesContext() { }
		public virtual void CopyFrom(CasesContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Cases_case_vbar_casesContext : CasesContext {
		[System.Diagnostics.DebuggerNonUserCode] public CaseContext @case() {
			return GetRuleContext<CaseContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VBAR() { return GetToken(FullUntypedParser.VBAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CasesContext cases() {
			return GetRuleContext<CasesContext>(0);
		}
		public Cases_case_vbar_casesContext(CasesContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCases_case_vbar_cases(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Cases_caseContext : CasesContext {
		[System.Diagnostics.DebuggerNonUserCode] public CaseContext @case() {
			return GetRuleContext<CaseContext>(0);
		}
		public Cases_caseContext(CasesContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCases_case(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CasesContext cases() {
		CasesContext _localctx = new CasesContext(Context, State);
		EnterRule(_localctx, 32, RULE_cases);
		try {
			State = 247;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
			case 1:
				_localctx = new Cases_caseContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 242;
				@case();
				}
				break;
			case 2:
				_localctx = new Cases_case_vbar_casesContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 243;
				@case();
				State = 244;
				Match(VBAR);
				State = 245;
				cases();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CaseContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LT() { return GetToken(FullUntypedParser.LT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LCID() { return GetTokens(FullUntypedParser.LCID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LCID(int i) {
			return GetToken(FullUntypedParser.LCID, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(FullUntypedParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GT() { return GetToken(FullUntypedParser.GT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DDARROW() { return GetToken(FullUntypedParser.DDARROW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ApptermContext appterm() {
			return GetRuleContext<ApptermContext>(0);
		}
		public CaseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_case; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCase(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CaseContext @case() {
		CaseContext _localctx = new CaseContext(Context, State);
		EnterRule(_localctx, 34, RULE_case);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 249;
			Match(LT);
			State = 250;
			Match(LCID);
			State = 251;
			Match(EQ);
			State = 252;
			Match(LCID);
			State = 253;
			Match(GT);
			State = 254;
			Match(DDARROW);
			State = 255;
			appterm(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NefieldsContext nefields() {
			return GetRuleContext<NefieldsContext>(0);
		}
		public FieldsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fields; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFields(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FieldsContext fields() {
		FieldsContext _localctx = new FieldsContext(Context, State);
		EnterRule(_localctx, 36, RULE_fields);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 258;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (((((_la - 2)) & ~0x3f) == 0 && ((1L << (_la - 2)) & 6341099061687708851L) != 0)) {
				{
				State = 257;
				nefields();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NefieldsContext : ParserRuleContext {
		public NefieldsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nefields; } }
	 
		public NefieldsContext() { }
		public virtual void CopyFrom(NefieldsContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Nefields_fieldContext : NefieldsContext {
		[System.Diagnostics.DebuggerNonUserCode] public FieldContext field() {
			return GetRuleContext<FieldContext>(0);
		}
		public Nefields_fieldContext(NefieldsContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNefields_field(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Nefields_field_comma_nefieldsContext : NefieldsContext {
		[System.Diagnostics.DebuggerNonUserCode] public FieldContext field() {
			return GetRuleContext<FieldContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA() { return GetToken(FullUntypedParser.COMMA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NefieldsContext nefields() {
			return GetRuleContext<NefieldsContext>(0);
		}
		public Nefields_field_comma_nefieldsContext(NefieldsContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNefields_field_comma_nefields(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NefieldsContext nefields() {
		NefieldsContext _localctx = new NefieldsContext(Context, State);
		EnterRule(_localctx, 38, RULE_nefields);
		try {
			State = 265;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,17,Context) ) {
			case 1:
				_localctx = new Nefields_fieldContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 260;
				field();
				}
				break;
			case 2:
				_localctx = new Nefields_field_comma_nefieldsContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 261;
				field();
				State = 262;
				Match(COMMA);
				State = 263;
				nefields();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldContext : ParserRuleContext {
		public FieldContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_field; } }
	 
		public FieldContext() { }
		public virtual void CopyFrom(FieldContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Field_termContext : FieldContext {
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public Field_termContext(FieldContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitField_term(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Field_lcidContext : FieldContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LCID() { return GetToken(FullUntypedParser.LCID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(FullUntypedParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public Field_lcidContext(FieldContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullUntypedVisitor<TResult> typedVisitor = visitor as IFullUntypedVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitField_lcid(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FieldContext field() {
		FieldContext _localctx = new FieldContext(Context, State);
		EnterRule(_localctx, 40, RULE_field);
		try {
			State = 271;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
			case 1:
				_localctx = new Field_lcidContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 267;
				Match(LCID);
				State = 268;
				Match(EQ);
				State = 269;
				term();
				}
				break;
			case 2:
				_localctx = new Field_termContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 270;
				term();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 11: return appterm_sempred((ApptermContext)_localctx, predIndex);
		case 13: return pathterm_sempred((PathtermContext)_localctx, predIndex);
		}
		return true;
	}
	private bool appterm_sempred(ApptermContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 6);
		}
		return true;
	}
	private bool pathterm_sempred(PathtermContext _localctx, int predIndex) {
		switch (predIndex) {
		case 1: return Precpred(Context, 3);
		case 2: return Precpred(Context, 2);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,68,274,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,1,0,1,0,1,
		0,1,0,1,0,3,0,48,8,0,1,1,1,1,1,1,1,1,1,1,3,1,55,8,1,1,2,1,2,1,2,1,2,3,
		2,61,8,2,1,3,1,3,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,
		4,1,4,1,4,1,4,1,4,3,4,83,8,4,1,5,1,5,1,5,1,6,1,6,1,7,1,7,1,7,1,7,1,7,3,
		7,95,8,7,1,8,1,8,1,8,1,8,3,8,101,8,8,1,9,1,9,1,9,1,9,1,9,3,9,108,8,9,1,
		10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,
		10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,
		10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,
		10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,3,10,160,8,10,1,11,1,11,1,11,1,11,
		1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,3,11,176,8,11,1,11,1,
		11,5,11,180,8,11,10,11,12,11,183,9,11,1,12,1,12,1,12,1,12,1,12,3,12,190,
		8,12,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,5,13,201,8,13,10,13,
		12,13,204,9,13,1,14,1,14,1,14,1,14,1,14,3,14,211,8,14,1,15,1,15,1,15,1,
		15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,
		15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,3,15,241,8,15,1,16,
		1,16,1,16,1,16,1,16,3,16,248,8,16,1,17,1,17,1,17,1,17,1,17,1,17,1,17,1,
		17,1,18,3,18,259,8,18,1,19,1,19,1,19,1,19,1,19,3,19,266,8,19,1,20,1,20,
		1,20,1,20,3,20,272,8,20,1,20,0,2,22,26,21,0,2,4,6,8,10,12,14,16,18,20,
		22,24,26,28,30,32,34,36,38,40,0,0,298,0,47,1,0,0,0,2,54,1,0,0,0,4,60,1,
		0,0,0,6,62,1,0,0,0,8,82,1,0,0,0,10,84,1,0,0,0,12,87,1,0,0,0,14,94,1,0,
		0,0,16,100,1,0,0,0,18,107,1,0,0,0,20,159,1,0,0,0,22,175,1,0,0,0,24,189,
		1,0,0,0,26,191,1,0,0,0,28,210,1,0,0,0,30,240,1,0,0,0,32,247,1,0,0,0,34,
		249,1,0,0,0,36,258,1,0,0,0,38,265,1,0,0,0,40,271,1,0,0,0,42,43,3,2,1,0,
		43,44,5,36,0,0,44,45,3,0,0,0,45,48,1,0,0,0,46,48,5,0,0,1,47,42,1,0,0,0,
		47,46,1,0,0,0,48,1,1,0,0,0,49,55,3,20,10,0,50,51,5,63,0,0,51,55,3,10,5,
		0,52,53,5,64,0,0,53,55,3,4,2,0,54,49,1,0,0,0,54,50,1,0,0,0,54,52,1,0,0,
		0,55,3,1,0,0,0,56,57,5,39,0,0,57,61,3,6,3,0,58,59,5,41,0,0,59,61,3,20,
		10,0,60,56,1,0,0,0,60,58,1,0,0,0,61,5,1,0,0,0,62,63,3,18,9,0,63,7,1,0,
		0,0,64,65,5,46,0,0,65,66,3,6,3,0,66,67,5,51,0,0,67,83,1,0,0,0,68,83,5,
		63,0,0,69,83,5,8,0,0,70,71,5,44,0,0,71,72,3,12,6,0,72,73,5,53,0,0,73,83,
		1,0,0,0,74,83,5,17,0,0,75,83,5,19,0,0,76,77,5,45,0,0,77,78,3,12,6,0,78,
		79,5,50,0,0,79,83,1,0,0,0,80,83,5,21,0,0,81,83,5,25,0,0,82,64,1,0,0,0,
		82,68,1,0,0,0,82,69,1,0,0,0,82,70,1,0,0,0,82,74,1,0,0,0,82,75,1,0,0,0,
		82,76,1,0,0,0,82,80,1,0,0,0,82,81,1,0,0,0,83,9,1,0,0,0,84,85,5,41,0,0,
		85,86,3,6,3,0,86,11,1,0,0,0,87,88,3,14,7,0,88,13,1,0,0,0,89,95,3,16,8,
		0,90,91,3,16,8,0,91,92,5,37,0,0,92,93,3,14,7,0,93,95,1,0,0,0,94,89,1,0,
		0,0,94,90,1,0,0,0,95,15,1,0,0,0,96,97,5,64,0,0,97,98,5,39,0,0,98,101,3,
		6,3,0,99,101,3,6,3,0,100,96,1,0,0,0,100,99,1,0,0,0,101,17,1,0,0,0,102,
		103,3,8,4,0,103,104,5,58,0,0,104,105,3,18,9,0,105,108,1,0,0,0,106,108,
		3,8,4,0,107,102,1,0,0,0,107,106,1,0,0,0,108,19,1,0,0,0,109,160,3,22,11,
		0,110,111,5,3,0,0,111,112,3,20,10,0,112,113,5,4,0,0,113,114,3,20,10,0,
		114,115,5,5,0,0,115,116,3,20,10,0,116,160,1,0,0,0,117,118,5,9,0,0,118,
		119,3,20,10,0,119,120,5,10,0,0,120,121,3,32,16,0,121,160,1,0,0,0,122,123,
		5,12,0,0,123,124,5,64,0,0,124,125,5,39,0,0,125,126,3,6,3,0,126,127,5,35,
		0,0,127,128,3,20,10,0,128,160,1,0,0,0,129,130,5,12,0,0,130,131,5,27,0,
		0,131,132,5,39,0,0,132,133,3,6,3,0,133,134,5,35,0,0,134,135,3,20,10,0,
		135,160,1,0,0,0,136,137,5,13,0,0,137,138,5,64,0,0,138,139,5,41,0,0,139,
		140,3,20,10,0,140,141,5,14,0,0,141,142,3,20,10,0,142,160,1,0,0,0,143,144,
		5,13,0,0,144,145,5,27,0,0,145,146,5,41,0,0,146,147,3,20,10,0,147,148,5,
		14,0,0,148,149,3,20,10,0,149,160,1,0,0,0,150,151,5,16,0,0,151,152,5,64,
		0,0,152,153,5,39,0,0,153,154,3,6,3,0,154,155,5,41,0,0,155,156,3,20,10,
		0,156,157,5,14,0,0,157,158,3,20,10,0,158,160,1,0,0,0,159,109,1,0,0,0,159,
		110,1,0,0,0,159,117,1,0,0,0,159,122,1,0,0,0,159,129,1,0,0,0,159,136,1,
		0,0,0,159,143,1,0,0,0,159,150,1,0,0,0,160,21,1,0,0,0,161,162,6,11,-1,0,
		162,176,3,26,13,0,163,164,5,15,0,0,164,176,3,26,13,0,165,166,5,20,0,0,
		166,167,3,26,13,0,167,168,3,26,13,0,168,176,1,0,0,0,169,170,5,22,0,0,170,
		176,3,26,13,0,171,172,5,23,0,0,172,176,3,26,13,0,173,174,5,24,0,0,174,
		176,3,26,13,0,175,161,1,0,0,0,175,163,1,0,0,0,175,165,1,0,0,0,175,169,
		1,0,0,0,175,171,1,0,0,0,175,173,1,0,0,0,176,181,1,0,0,0,177,178,10,6,0,
		0,178,180,3,26,13,0,179,177,1,0,0,0,180,183,1,0,0,0,181,179,1,0,0,0,181,
		182,1,0,0,0,182,23,1,0,0,0,183,181,1,0,0,0,184,185,3,30,15,0,185,186,5,
		11,0,0,186,187,3,6,3,0,187,190,1,0,0,0,188,190,3,30,15,0,189,184,1,0,0,
		0,189,188,1,0,0,0,190,25,1,0,0,0,191,192,6,13,-1,0,192,193,3,24,12,0,193,
		202,1,0,0,0,194,195,10,3,0,0,195,196,5,35,0,0,196,201,5,64,0,0,197,198,
		10,2,0,0,198,199,5,35,0,0,199,201,5,62,0,0,200,194,1,0,0,0,200,197,1,0,
		0,0,201,204,1,0,0,0,202,200,1,0,0,0,202,203,1,0,0,0,203,27,1,0,0,0,204,
		202,1,0,0,0,205,211,3,20,10,0,206,207,3,20,10,0,207,208,5,36,0,0,208,209,
		3,28,14,0,209,211,1,0,0,0,210,205,1,0,0,0,210,206,1,0,0,0,211,29,1,0,0,
		0,212,213,5,46,0,0,213,214,3,28,14,0,214,215,5,51,0,0,215,241,1,0,0,0,
		216,217,5,2,0,0,217,218,5,43,0,0,218,219,3,6,3,0,219,220,5,52,0,0,220,
		241,1,0,0,0,221,241,5,6,0,0,222,241,5,7,0,0,223,224,5,44,0,0,224,225,5,
		64,0,0,225,226,5,41,0,0,226,227,3,20,10,0,227,228,5,53,0,0,228,229,5,11,
		0,0,229,230,3,6,3,0,230,241,1,0,0,0,231,241,5,64,0,0,232,241,5,26,0,0,
		233,241,5,18,0,0,234,235,5,45,0,0,235,236,3,36,18,0,236,237,5,50,0,0,237,
		241,1,0,0,0,238,241,5,61,0,0,239,241,5,62,0,0,240,212,1,0,0,0,240,216,
		1,0,0,0,240,221,1,0,0,0,240,222,1,0,0,0,240,223,1,0,0,0,240,231,1,0,0,
		0,240,232,1,0,0,0,240,233,1,0,0,0,240,234,1,0,0,0,240,238,1,0,0,0,240,
		239,1,0,0,0,241,31,1,0,0,0,242,248,3,34,17,0,243,244,3,34,17,0,244,245,
		5,34,0,0,245,246,3,32,16,0,246,248,1,0,0,0,247,242,1,0,0,0,247,243,1,0,
		0,0,248,33,1,0,0,0,249,250,5,44,0,0,250,251,5,64,0,0,251,252,5,41,0,0,
		252,253,5,64,0,0,253,254,5,53,0,0,254,255,5,60,0,0,255,256,3,22,11,0,256,
		35,1,0,0,0,257,259,3,38,19,0,258,257,1,0,0,0,258,259,1,0,0,0,259,37,1,
		0,0,0,260,266,3,40,20,0,261,262,3,40,20,0,262,263,5,37,0,0,263,264,3,38,
		19,0,264,266,1,0,0,0,265,260,1,0,0,0,265,261,1,0,0,0,266,39,1,0,0,0,267,
		268,5,64,0,0,268,269,5,41,0,0,269,272,3,20,10,0,270,272,3,20,10,0,271,
		267,1,0,0,0,271,270,1,0,0,0,272,41,1,0,0,0,19,47,54,60,82,94,100,107,159,
		175,181,189,200,202,210,240,247,258,265,271
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
