//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /tmp/FullRef.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FullRefParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IFullRefVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FullRefParser.toplevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToplevel([NotNull] FullRefParser.ToplevelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>command_term</c>
	/// labeled alternative in <see cref="FullRefParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand_term([NotNull] FullRefParser.Command_termContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>command_tybinder</c>
	/// labeled alternative in <see cref="FullRefParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand_tybinder([NotNull] FullRefParser.Command_tybinderContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>command_binder</c>
	/// labeled alternative in <see cref="FullRefParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand_binder([NotNull] FullRefParser.Command_binderContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binder_type</c>
	/// labeled alternative in <see cref="FullRefParser.binder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinder_type([NotNull] FullRefParser.Binder_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binder_term</c>
	/// labeled alternative in <see cref="FullRefParser.binder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinder_term([NotNull] FullRefParser.Binder_termContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>type_arrowtype</c>
	/// labeled alternative in <see cref="FullRefParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_arrowtype([NotNull] FullRefParser.Type_arrowtypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>type_ref</c>
	/// labeled alternative in <see cref="FullRefParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_ref([NotNull] FullRefParser.Type_refContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>type_source</c>
	/// labeled alternative in <see cref="FullRefParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_source([NotNull] FullRefParser.Type_sourceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>type_sink</c>
	/// labeled alternative in <see cref="FullRefParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_sink([NotNull] FullRefParser.Type_sinkContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_type</c>
	/// labeled alternative in <see cref="FullRefParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_type([NotNull] FullRefParser.At_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_tbot</c>
	/// labeled alternative in <see cref="FullRefParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_tbot([NotNull] FullRefParser.At_tbotContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_ttop</c>
	/// labeled alternative in <see cref="FullRefParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_ttop([NotNull] FullRefParser.At_ttopContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_ucid</c>
	/// labeled alternative in <see cref="FullRefParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_ucid([NotNull] FullRefParser.At_ucidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_bool</c>
	/// labeled alternative in <see cref="FullRefParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_bool([NotNull] FullRefParser.At_boolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_variant</c>
	/// labeled alternative in <see cref="FullRefParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_variant([NotNull] FullRefParser.At_variantContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_ustring</c>
	/// labeled alternative in <see cref="FullRefParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_ustring([NotNull] FullRefParser.At_ustringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_uunit</c>
	/// labeled alternative in <see cref="FullRefParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_uunit([NotNull] FullRefParser.At_uunitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_record</c>
	/// labeled alternative in <see cref="FullRefParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_record([NotNull] FullRefParser.At_recordContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_ufloat</c>
	/// labeled alternative in <see cref="FullRefParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_ufloat([NotNull] FullRefParser.At_ufloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_nat</c>
	/// labeled alternative in <see cref="FullRefParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_nat([NotNull] FullRefParser.At_natContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>tybinder_type</c>
	/// labeled alternative in <see cref="FullRefParser.tybinder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTybinder_type([NotNull] FullRefParser.Tybinder_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>fieldtypes_nefieldtypes</c>
	/// labeled alternative in <see cref="FullRefParser.fieldtypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldtypes_nefieldtypes([NotNull] FullRefParser.Fieldtypes_nefieldtypesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nefieldtypes_fieldtype</c>
	/// labeled alternative in <see cref="FullRefParser.nefieldtypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNefieldtypes_fieldtype([NotNull] FullRefParser.Nefieldtypes_fieldtypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nefieldtypes_nefieldtype</c>
	/// labeled alternative in <see cref="FullRefParser.nefieldtypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNefieldtypes_nefieldtype([NotNull] FullRefParser.Nefieldtypes_nefieldtypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>fieldtype_lcid</c>
	/// labeled alternative in <see cref="FullRefParser.fieldtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldtype_lcid([NotNull] FullRefParser.Fieldtype_lcidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>fieldtype_type</c>
	/// labeled alternative in <see cref="FullRefParser.fieldtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldtype_type([NotNull] FullRefParser.Fieldtype_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arrowtype_arrow</c>
	/// labeled alternative in <see cref="FullRefParser.arrowtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrowtype_arrow([NotNull] FullRefParser.Arrowtype_arrowContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arrowtype_atype</c>
	/// labeled alternative in <see cref="FullRefParser.arrowtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrowtype_atype([NotNull] FullRefParser.Arrowtype_atypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_appterm</c>
	/// labeled alternative in <see cref="FullRefParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_appterm([NotNull] FullRefParser.Term_apptermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_ift</c>
	/// labeled alternative in <see cref="FullRefParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_ift([NotNull] FullRefParser.Term_iftContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_assign</c>
	/// labeled alternative in <see cref="FullRefParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_assign([NotNull] FullRefParser.Term_assignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_caseOf</c>
	/// labeled alternative in <see cref="FullRefParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_caseOf([NotNull] FullRefParser.Term_caseOfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_llcid</c>
	/// labeled alternative in <see cref="FullRefParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_llcid([NotNull] FullRefParser.Term_llcidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_luc</c>
	/// labeled alternative in <see cref="FullRefParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_luc([NotNull] FullRefParser.Term_lucContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_ll</c>
	/// labeled alternative in <see cref="FullRefParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_ll([NotNull] FullRefParser.Term_llContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_lu</c>
	/// labeled alternative in <see cref="FullRefParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_lu([NotNull] FullRefParser.Term_luContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_letrec</c>
	/// labeled alternative in <see cref="FullRefParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_letrec([NotNull] FullRefParser.Term_letrecContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_times</c>
	/// labeled alternative in <see cref="FullRefParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_times([NotNull] FullRefParser.Appterm_timesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_iszero</c>
	/// labeled alternative in <see cref="FullRefParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_iszero([NotNull] FullRefParser.Appterm_iszeroContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_path</c>
	/// labeled alternative in <see cref="FullRefParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_path([NotNull] FullRefParser.Appterm_pathContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_app_path</c>
	/// labeled alternative in <see cref="FullRefParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_app_path([NotNull] FullRefParser.Appterm_app_pathContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_succ</c>
	/// labeled alternative in <see cref="FullRefParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_succ([NotNull] FullRefParser.Appterm_succContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_ref</c>
	/// labeled alternative in <see cref="FullRefParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_ref([NotNull] FullRefParser.Appterm_refContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_deref</c>
	/// labeled alternative in <see cref="FullRefParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_deref([NotNull] FullRefParser.Appterm_derefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_pred</c>
	/// labeled alternative in <see cref="FullRefParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_pred([NotNull] FullRefParser.Appterm_predContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_fix</c>
	/// labeled alternative in <see cref="FullRefParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_fix([NotNull] FullRefParser.Appterm_fixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ascribeterm_aaa</c>
	/// labeled alternative in <see cref="FullRefParser.ascribeterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAscribeterm_aaa([NotNull] FullRefParser.Ascribeterm_aaaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ascribeterm_a</c>
	/// labeled alternative in <see cref="FullRefParser.ascribeterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAscribeterm_a([NotNull] FullRefParser.Ascribeterm_aContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pathterm_intv</c>
	/// labeled alternative in <see cref="FullRefParser.pathterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPathterm_intv([NotNull] FullRefParser.Pathterm_intvContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pathterm_lcid</c>
	/// labeled alternative in <see cref="FullRefParser.pathterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPathterm_lcid([NotNull] FullRefParser.Pathterm_lcidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pathterm_asterm</c>
	/// labeled alternative in <see cref="FullRefParser.pathterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPathterm_asterm([NotNull] FullRefParser.Pathterm_astermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>termseq_term</c>
	/// labeled alternative in <see cref="FullRefParser.termseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermseq_term([NotNull] FullRefParser.Termseq_termContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>termseq_termseq</c>
	/// labeled alternative in <see cref="FullRefParser.termseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermseq_termseq([NotNull] FullRefParser.Termseq_termseqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_paren</c>
	/// labeled alternative in <see cref="FullRefParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_paren([NotNull] FullRefParser.Aterm_parenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_inert</c>
	/// labeled alternative in <see cref="FullRefParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_inert([NotNull] FullRefParser.Aterm_inertContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_true</c>
	/// labeled alternative in <see cref="FullRefParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_true([NotNull] FullRefParser.Aterm_trueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_false</c>
	/// labeled alternative in <see cref="FullRefParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_false([NotNull] FullRefParser.Aterm_falseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_lt</c>
	/// labeled alternative in <see cref="FullRefParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_lt([NotNull] FullRefParser.Aterm_ltContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_lcid</c>
	/// labeled alternative in <see cref="FullRefParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_lcid([NotNull] FullRefParser.Aterm_lcidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_stringv</c>
	/// labeled alternative in <see cref="FullRefParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_stringv([NotNull] FullRefParser.Aterm_stringvContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_unit</c>
	/// labeled alternative in <see cref="FullRefParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_unit([NotNull] FullRefParser.Aterm_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_fields</c>
	/// labeled alternative in <see cref="FullRefParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_fields([NotNull] FullRefParser.Aterm_fieldsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_floatv</c>
	/// labeled alternative in <see cref="FullRefParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_floatv([NotNull] FullRefParser.Aterm_floatvContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_intv</c>
	/// labeled alternative in <see cref="FullRefParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_intv([NotNull] FullRefParser.Aterm_intvContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>cases_case</c>
	/// labeled alternative in <see cref="FullRefParser.cases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCases_case([NotNull] FullRefParser.Cases_caseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>cases_case_vbar_cases</c>
	/// labeled alternative in <see cref="FullRefParser.cases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCases_case_vbar_cases([NotNull] FullRefParser.Cases_case_vbar_casesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FullRefParser.case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase([NotNull] FullRefParser.CaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FullRefParser.fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFields([NotNull] FullRefParser.FieldsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nefields_field</c>
	/// labeled alternative in <see cref="FullRefParser.nefields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNefields_field([NotNull] FullRefParser.Nefields_fieldContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nefields_field_comma_nefields</c>
	/// labeled alternative in <see cref="FullRefParser.nefields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNefields_field_comma_nefields([NotNull] FullRefParser.Nefields_field_comma_nefieldsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>field_lcid</c>
	/// labeled alternative in <see cref="FullRefParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField_lcid([NotNull] FullRefParser.Field_lcidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>field_term</c>
	/// labeled alternative in <see cref="FullRefParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField_term([NotNull] FullRefParser.Field_termContext context);
}
