//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FullError.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FullErrorParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IFullErrorVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FullErrorParser.toplevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToplevel([NotNull] FullErrorParser.ToplevelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>command_term</c>
	/// labeled alternative in <see cref="FullErrorParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand_term([NotNull] FullErrorParser.Command_termContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>command_tybinder</c>
	/// labeled alternative in <see cref="FullErrorParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand_tybinder([NotNull] FullErrorParser.Command_tybinderContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>command_binder</c>
	/// labeled alternative in <see cref="FullErrorParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand_binder([NotNull] FullErrorParser.Command_binderContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binder_type</c>
	/// labeled alternative in <see cref="FullErrorParser.binder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinder_type([NotNull] FullErrorParser.Binder_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binder_term</c>
	/// labeled alternative in <see cref="FullErrorParser.binder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinder_term([NotNull] FullErrorParser.Binder_termContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>type_arrowtype</c>
	/// labeled alternative in <see cref="FullErrorParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_arrowtype([NotNull] FullErrorParser.Type_arrowtypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_type</c>
	/// labeled alternative in <see cref="FullErrorParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_type([NotNull] FullErrorParser.At_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_bot</c>
	/// labeled alternative in <see cref="FullErrorParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_bot([NotNull] FullErrorParser.At_botContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_top</c>
	/// labeled alternative in <see cref="FullErrorParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_top([NotNull] FullErrorParser.At_topContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_bool</c>
	/// labeled alternative in <see cref="FullErrorParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_bool([NotNull] FullErrorParser.At_boolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>at_ucid</c>
	/// labeled alternative in <see cref="FullErrorParser.atype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAt_ucid([NotNull] FullErrorParser.At_ucidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arrowtype_arrow</c>
	/// labeled alternative in <see cref="FullErrorParser.arrowtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrowtype_arrow([NotNull] FullErrorParser.Arrowtype_arrowContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arrowtype_atype</c>
	/// labeled alternative in <see cref="FullErrorParser.arrowtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrowtype_atype([NotNull] FullErrorParser.Arrowtype_atypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_appterm</c>
	/// labeled alternative in <see cref="FullErrorParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_appterm([NotNull] FullErrorParser.Term_apptermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_ift</c>
	/// labeled alternative in <see cref="FullErrorParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_ift([NotNull] FullErrorParser.Term_iftContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_llcid</c>
	/// labeled alternative in <see cref="FullErrorParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_llcid([NotNull] FullErrorParser.Term_llcidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_luc</c>
	/// labeled alternative in <see cref="FullErrorParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_luc([NotNull] FullErrorParser.Term_lucContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>term_try</c>
	/// labeled alternative in <see cref="FullErrorParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_try([NotNull] FullErrorParser.Term_tryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_aterm</c>
	/// labeled alternative in <see cref="FullErrorParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_aterm([NotNull] FullErrorParser.Appterm_atermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>appterm_app</c>
	/// labeled alternative in <see cref="FullErrorParser.appterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppterm_app([NotNull] FullErrorParser.Appterm_appContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_paren</c>
	/// labeled alternative in <see cref="FullErrorParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_paren([NotNull] FullErrorParser.Aterm_parenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_lcid</c>
	/// labeled alternative in <see cref="FullErrorParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_lcid([NotNull] FullErrorParser.Aterm_lcidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_true</c>
	/// labeled alternative in <see cref="FullErrorParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_true([NotNull] FullErrorParser.Aterm_trueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_false</c>
	/// labeled alternative in <see cref="FullErrorParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_false([NotNull] FullErrorParser.Aterm_falseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aterm_error</c>
	/// labeled alternative in <see cref="FullErrorParser.aterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAterm_error([NotNull] FullErrorParser.Aterm_errorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>tybinder_empty</c>
	/// labeled alternative in <see cref="FullErrorParser.tybinder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTybinder_empty([NotNull] FullErrorParser.Tybinder_emptyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>tybinder_type</c>
	/// labeled alternative in <see cref="FullErrorParser.tybinder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTybinder_type([NotNull] FullErrorParser.Tybinder_typeContext context);
}
