//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FullError.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class FullErrorParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		TBOT=1, TTOP=2, IF=3, THEN=4, ELSE=5, TRUE=6, FALSE=7, BOOL=8, LAMBDA=9, 
		ERROR=10, TRY=11, OTHERWISE=12, TYPE=13, USCORE=14, APOSTROPHE=15, DQUOTE=16, 
		BANG=17, HASH=18, TRIANGLE=19, STAR=20, VBAR=21, DOT=22, SEMI=23, COMMA=24, 
		SLASH=25, COLON=26, COLONCOLON=27, EQ=28, EQEQ=29, LSQUARE=30, LT=31, 
		LCURLY=32, LPAREN=33, LEFTARROW=34, LCURLYBAR=35, LSQUAREBAR=36, RCURLY=37, 
		RPAREN=38, RSQUARE=39, GT=40, BARRCURLY=41, BARGT=42, BARRSQUARE=43, COLONEQ=44, 
		ARROW=45, DARROW=46, DDARROW=47, INTV=48, UCID=49, LCID=50, WS=51, TAB=52, 
		NL=53, NL1=54, COMMENT=55;
	public const int
		RULE_toplevel = 0, RULE_command = 1, RULE_binder = 2, RULE_type = 3, RULE_atype = 4, 
		RULE_arrowtype = 5, RULE_term = 6, RULE_appterm = 7, RULE_aterm = 8, RULE_tybinder = 9;
	public static readonly string[] ruleNames = {
		"toplevel", "command", "binder", "type", "atype", "arrowtype", "term", 
		"appterm", "aterm", "tybinder"
	};

	private static readonly string[] _LiteralNames = {
		null, "'Bot'", "'Top'", "'if'", "'then'", "'else'", "'true'", "'false'", 
		"'Bool'", "'lambda'", "'error'", "'try'", "'with'", "'type'", "'_'", "'''", 
		"'\"'", "'!'", "'#'", "'$'", "'*'", "'|'", "'.'", "';'", "','", "'/'", 
		"':'", "'::'", "'='", "'=='", "'['", "'<'", "'{'", "'('", "'<-'", "'{|'", 
		"'[|'", "'}'", "')'", "']'", "'>'", "'|}'", "'|>'", "'|]'", "':='", "'->'", 
		"'=>'", "'==>'", null, null, null, "' '", "'\\t'", "'\\r'", "'\\n'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "TBOT", "TTOP", "IF", "THEN", "ELSE", "TRUE", "FALSE", "BOOL", "LAMBDA", 
		"ERROR", "TRY", "OTHERWISE", "TYPE", "USCORE", "APOSTROPHE", "DQUOTE", 
		"BANG", "HASH", "TRIANGLE", "STAR", "VBAR", "DOT", "SEMI", "COMMA", "SLASH", 
		"COLON", "COLONCOLON", "EQ", "EQEQ", "LSQUARE", "LT", "LCURLY", "LPAREN", 
		"LEFTARROW", "LCURLYBAR", "LSQUAREBAR", "RCURLY", "RPAREN", "RSQUARE", 
		"GT", "BARRCURLY", "BARGT", "BARRSQUARE", "COLONEQ", "ARROW", "DARROW", 
		"DDARROW", "INTV", "UCID", "LCID", "WS", "TAB", "NL", "NL1", "COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "FullError.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static FullErrorParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public FullErrorParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public FullErrorParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ToplevelContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public CommandContext command() {
			return GetRuleContext<CommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(FullErrorParser.SEMI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ToplevelContext toplevel() {
			return GetRuleContext<ToplevelContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(FullErrorParser.Eof, 0); }
		public ToplevelContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_toplevel; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitToplevel(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ToplevelContext toplevel() {
		ToplevelContext _localctx = new ToplevelContext(Context, State);
		EnterRule(_localctx, 0, RULE_toplevel);
		try {
			State = 25;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IF:
			case TRUE:
			case FALSE:
			case LAMBDA:
			case ERROR:
			case TRY:
			case LPAREN:
			case UCID:
			case LCID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 20;
				command();
				State = 21;
				Match(SEMI);
				State = 22;
				toplevel();
				}
				break;
			case Eof:
				EnterOuterAlt(_localctx, 2);
				{
				State = 24;
				Match(Eof);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommandContext : ParserRuleContext {
		public CommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_command; } }
	 
		public CommandContext() { }
		public virtual void CopyFrom(CommandContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Command_binderContext : CommandContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LCID() { return GetToken(FullErrorParser.LCID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BinderContext binder() {
			return GetRuleContext<BinderContext>(0);
		}
		public Command_binderContext(CommandContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCommand_binder(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Command_termContext : CommandContext {
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public Command_termContext(CommandContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCommand_term(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Command_tybinderContext : CommandContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UCID() { return GetToken(FullErrorParser.UCID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TybinderContext tybinder() {
			return GetRuleContext<TybinderContext>(0);
		}
		public Command_tybinderContext(CommandContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCommand_tybinder(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CommandContext command() {
		CommandContext _localctx = new CommandContext(Context, State);
		EnterRule(_localctx, 2, RULE_command);
		try {
			State = 32;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				_localctx = new Command_termContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 27;
				term();
				}
				break;
			case 2:
				_localctx = new Command_tybinderContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 28;
				Match(UCID);
				State = 29;
				tybinder();
				}
				break;
			case 3:
				_localctx = new Command_binderContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 30;
				Match(LCID);
				State = 31;
				binder();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BinderContext : ParserRuleContext {
		public BinderContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_binder; } }
	 
		public BinderContext() { }
		public virtual void CopyFrom(BinderContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Binder_termContext : BinderContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(FullErrorParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public Binder_termContext(BinderContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinder_term(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Binder_typeContext : BinderContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(FullErrorParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public Binder_typeContext(BinderContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinder_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BinderContext binder() {
		BinderContext _localctx = new BinderContext(Context, State);
		EnterRule(_localctx, 4, RULE_binder);
		try {
			State = 38;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case COLON:
				_localctx = new Binder_typeContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 34;
				Match(COLON);
				State = 35;
				type();
				}
				break;
			case EQ:
				_localctx = new Binder_termContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 36;
				Match(EQ);
				State = 37;
				term();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContext : ParserRuleContext {
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
	 
		public TypeContext() { }
		public virtual void CopyFrom(TypeContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Type_arrowtypeContext : TypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArrowtypeContext arrowtype() {
			return GetRuleContext<ArrowtypeContext>(0);
		}
		public Type_arrowtypeContext(TypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType_arrowtype(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeContext type() {
		TypeContext _localctx = new TypeContext(Context, State);
		EnterRule(_localctx, 6, RULE_type);
		try {
			_localctx = new Type_arrowtypeContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 40;
			arrowtype();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AtypeContext : ParserRuleContext {
		public AtypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atype; } }
	 
		public AtypeContext() { }
		public virtual void CopyFrom(AtypeContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class At_boolContext : AtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOL() { return GetToken(FullErrorParser.BOOL, 0); }
		public At_boolContext(AtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAt_bool(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class At_ucidContext : AtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UCID() { return GetToken(FullErrorParser.UCID, 0); }
		public At_ucidContext(AtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAt_ucid(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class At_typeContext : AtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(FullErrorParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(FullErrorParser.RPAREN, 0); }
		public At_typeContext(AtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAt_type(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class At_topContext : AtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TTOP() { return GetToken(FullErrorParser.TTOP, 0); }
		public At_topContext(AtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAt_top(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class At_botContext : AtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TBOT() { return GetToken(FullErrorParser.TBOT, 0); }
		public At_botContext(AtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAt_bot(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AtypeContext atype() {
		AtypeContext _localctx = new AtypeContext(Context, State);
		EnterRule(_localctx, 8, RULE_atype);
		try {
			State = 50;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LPAREN:
				_localctx = new At_typeContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 42;
				Match(LPAREN);
				State = 43;
				type();
				State = 44;
				Match(RPAREN);
				}
				break;
			case TBOT:
				_localctx = new At_botContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 46;
				Match(TBOT);
				}
				break;
			case TTOP:
				_localctx = new At_topContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 47;
				Match(TTOP);
				}
				break;
			case BOOL:
				_localctx = new At_boolContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 48;
				Match(BOOL);
				}
				break;
			case UCID:
				_localctx = new At_ucidContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 49;
				Match(UCID);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrowtypeContext : ParserRuleContext {
		public ArrowtypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arrowtype; } }
	 
		public ArrowtypeContext() { }
		public virtual void CopyFrom(ArrowtypeContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Arrowtype_atypeContext : ArrowtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public AtypeContext atype() {
			return GetRuleContext<AtypeContext>(0);
		}
		public Arrowtype_atypeContext(ArrowtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrowtype_atype(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Arrowtype_arrowContext : ArrowtypeContext {
		[System.Diagnostics.DebuggerNonUserCode] public AtypeContext atype() {
			return GetRuleContext<AtypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ARROW() { return GetToken(FullErrorParser.ARROW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArrowtypeContext arrowtype() {
			return GetRuleContext<ArrowtypeContext>(0);
		}
		public Arrowtype_arrowContext(ArrowtypeContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrowtype_arrow(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArrowtypeContext arrowtype() {
		ArrowtypeContext _localctx = new ArrowtypeContext(Context, State);
		EnterRule(_localctx, 10, RULE_arrowtype);
		try {
			State = 57;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				_localctx = new Arrowtype_arrowContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 52;
				atype();
				State = 53;
				Match(ARROW);
				State = 54;
				arrowtype();
				}
				break;
			case 2:
				_localctx = new Arrowtype_atypeContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 56;
				atype();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TermContext : ParserRuleContext {
		public TermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_term; } }
	 
		public TermContext() { }
		public virtual void CopyFrom(TermContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Term_lucContext : TermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LAMBDA() { return GetToken(FullErrorParser.LAMBDA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode USCORE() { return GetToken(FullErrorParser.USCORE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(FullErrorParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT() { return GetToken(FullErrorParser.DOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public Term_lucContext(TermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTerm_luc(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Term_apptermContext : TermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ApptermContext appterm() {
			return GetRuleContext<ApptermContext>(0);
		}
		public Term_apptermContext(TermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTerm_appterm(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Term_iftContext : TermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(FullErrorParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermContext[] term() {
			return GetRuleContexts<TermContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term(int i) {
			return GetRuleContext<TermContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode THEN() { return GetToken(FullErrorParser.THEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(FullErrorParser.ELSE, 0); }
		public Term_iftContext(TermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTerm_ift(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Term_tryContext : TermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRY() { return GetToken(FullErrorParser.TRY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermContext[] term() {
			return GetRuleContexts<TermContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term(int i) {
			return GetRuleContext<TermContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OTHERWISE() { return GetToken(FullErrorParser.OTHERWISE, 0); }
		public Term_tryContext(TermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTerm_try(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Term_llcidContext : TermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LAMBDA() { return GetToken(FullErrorParser.LAMBDA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LCID() { return GetToken(FullErrorParser.LCID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(FullErrorParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT() { return GetToken(FullErrorParser.DOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public Term_llcidContext(TermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTerm_llcid(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TermContext term() {
		TermContext _localctx = new TermContext(Context, State);
		EnterRule(_localctx, 12, RULE_term);
		try {
			State = 86;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				_localctx = new Term_apptermContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 59;
				appterm(0);
				}
				break;
			case 2:
				_localctx = new Term_iftContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 60;
				Match(IF);
				State = 61;
				term();
				State = 62;
				Match(THEN);
				State = 63;
				term();
				State = 64;
				Match(ELSE);
				State = 65;
				term();
				}
				break;
			case 3:
				_localctx = new Term_llcidContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 67;
				Match(LAMBDA);
				State = 68;
				Match(LCID);
				State = 69;
				Match(COLON);
				State = 70;
				type();
				State = 71;
				Match(DOT);
				State = 72;
				term();
				}
				break;
			case 4:
				_localctx = new Term_lucContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 74;
				Match(LAMBDA);
				State = 75;
				Match(USCORE);
				State = 76;
				Match(COLON);
				State = 77;
				type();
				State = 78;
				Match(DOT);
				State = 79;
				term();
				}
				break;
			case 5:
				_localctx = new Term_tryContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 81;
				Match(TRY);
				State = 82;
				term();
				State = 83;
				Match(OTHERWISE);
				State = 84;
				term();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ApptermContext : ParserRuleContext {
		public ApptermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_appterm; } }
	 
		public ApptermContext() { }
		public virtual void CopyFrom(ApptermContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Appterm_atermContext : ApptermContext {
		[System.Diagnostics.DebuggerNonUserCode] public AtermContext aterm() {
			return GetRuleContext<AtermContext>(0);
		}
		public Appterm_atermContext(ApptermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAppterm_aterm(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Appterm_appContext : ApptermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ApptermContext appterm() {
			return GetRuleContext<ApptermContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AtermContext aterm() {
			return GetRuleContext<AtermContext>(0);
		}
		public Appterm_appContext(ApptermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAppterm_app(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ApptermContext appterm() {
		return appterm(0);
	}

	private ApptermContext appterm(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ApptermContext _localctx = new ApptermContext(Context, _parentState);
		ApptermContext _prevctx = _localctx;
		int _startState = 14;
		EnterRecursionRule(_localctx, 14, RULE_appterm, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			_localctx = new Appterm_atermContext(_localctx);
			Context = _localctx;
			_prevctx = _localctx;

			State = 89;
			aterm();
			}
			Context.Stop = TokenStream.LT(-1);
			State = 95;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new Appterm_appContext(new ApptermContext(_parentctx, _parentState));
					PushNewRecursionContext(_localctx, _startState, RULE_appterm);
					State = 91;
					if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
					State = 92;
					aterm();
					}
					} 
				}
				State = 97;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class AtermContext : ParserRuleContext {
		public AtermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_aterm; } }
	 
		public AtermContext() { }
		public virtual void CopyFrom(AtermContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Aterm_falseContext : AtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FALSE() { return GetToken(FullErrorParser.FALSE, 0); }
		public Aterm_falseContext(AtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAterm_false(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Aterm_lcidContext : AtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LCID() { return GetToken(FullErrorParser.LCID, 0); }
		public Aterm_lcidContext(AtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAterm_lcid(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Aterm_trueContext : AtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRUE() { return GetToken(FullErrorParser.TRUE, 0); }
		public Aterm_trueContext(AtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAterm_true(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Aterm_parenContext : AtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(FullErrorParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(FullErrorParser.RPAREN, 0); }
		public Aterm_parenContext(AtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAterm_paren(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Aterm_errorContext : AtermContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ERROR() { return GetToken(FullErrorParser.ERROR, 0); }
		public Aterm_errorContext(AtermContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAterm_error(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AtermContext aterm() {
		AtermContext _localctx = new AtermContext(Context, State);
		EnterRule(_localctx, 16, RULE_aterm);
		try {
			State = 106;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LPAREN:
				_localctx = new Aterm_parenContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 98;
				Match(LPAREN);
				State = 99;
				term();
				State = 100;
				Match(RPAREN);
				}
				break;
			case LCID:
				_localctx = new Aterm_lcidContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 102;
				Match(LCID);
				}
				break;
			case TRUE:
				_localctx = new Aterm_trueContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 103;
				Match(TRUE);
				}
				break;
			case FALSE:
				_localctx = new Aterm_falseContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 104;
				Match(FALSE);
				}
				break;
			case ERROR:
				_localctx = new Aterm_errorContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 105;
				Match(ERROR);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TybinderContext : ParserRuleContext {
		public TybinderContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tybinder; } }
	 
		public TybinderContext() { }
		public virtual void CopyFrom(TybinderContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Tybinder_typeContext : TybinderContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(FullErrorParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public Tybinder_typeContext(TybinderContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTybinder_type(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Tybinder_emptyContext : TybinderContext {
		public Tybinder_emptyContext(TybinderContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFullErrorVisitor<TResult> typedVisitor = visitor as IFullErrorVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTybinder_empty(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TybinderContext tybinder() {
		TybinderContext _localctx = new TybinderContext(Context, State);
		EnterRule(_localctx, 18, RULE_tybinder);
		try {
			State = 111;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case SEMI:
				_localctx = new Tybinder_emptyContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				}
				break;
			case EQ:
				_localctx = new Tybinder_typeContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 109;
				Match(EQ);
				State = 110;
				type();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 7: return appterm_sempred((ApptermContext)_localctx, predIndex);
		}
		return true;
	}
	private bool appterm_sempred(ApptermContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 1);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,55,114,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,1,0,1,0,1,0,1,0,1,0,3,0,26,8,0,1,1,1,1,1,1,1,1,1,1,
		3,1,33,8,1,1,2,1,2,1,2,1,2,3,2,39,8,2,1,3,1,3,1,4,1,4,1,4,1,4,1,4,1,4,
		1,4,1,4,3,4,51,8,4,1,5,1,5,1,5,1,5,1,5,3,5,58,8,5,1,6,1,6,1,6,1,6,1,6,
		1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,
		6,1,6,1,6,1,6,1,6,3,6,87,8,6,1,7,1,7,1,7,1,7,1,7,5,7,94,8,7,10,7,12,7,
		97,9,7,1,8,1,8,1,8,1,8,1,8,1,8,1,8,1,8,3,8,107,8,8,1,9,1,9,1,9,3,9,112,
		8,9,1,9,0,1,14,10,0,2,4,6,8,10,12,14,16,18,0,0,122,0,25,1,0,0,0,2,32,1,
		0,0,0,4,38,1,0,0,0,6,40,1,0,0,0,8,50,1,0,0,0,10,57,1,0,0,0,12,86,1,0,0,
		0,14,88,1,0,0,0,16,106,1,0,0,0,18,111,1,0,0,0,20,21,3,2,1,0,21,22,5,23,
		0,0,22,23,3,0,0,0,23,26,1,0,0,0,24,26,5,0,0,1,25,20,1,0,0,0,25,24,1,0,
		0,0,26,1,1,0,0,0,27,33,3,12,6,0,28,29,5,49,0,0,29,33,3,18,9,0,30,31,5,
		50,0,0,31,33,3,4,2,0,32,27,1,0,0,0,32,28,1,0,0,0,32,30,1,0,0,0,33,3,1,
		0,0,0,34,35,5,26,0,0,35,39,3,6,3,0,36,37,5,28,0,0,37,39,3,12,6,0,38,34,
		1,0,0,0,38,36,1,0,0,0,39,5,1,0,0,0,40,41,3,10,5,0,41,7,1,0,0,0,42,43,5,
		33,0,0,43,44,3,6,3,0,44,45,5,38,0,0,45,51,1,0,0,0,46,51,5,1,0,0,47,51,
		5,2,0,0,48,51,5,8,0,0,49,51,5,49,0,0,50,42,1,0,0,0,50,46,1,0,0,0,50,47,
		1,0,0,0,50,48,1,0,0,0,50,49,1,0,0,0,51,9,1,0,0,0,52,53,3,8,4,0,53,54,5,
		45,0,0,54,55,3,10,5,0,55,58,1,0,0,0,56,58,3,8,4,0,57,52,1,0,0,0,57,56,
		1,0,0,0,58,11,1,0,0,0,59,87,3,14,7,0,60,61,5,3,0,0,61,62,3,12,6,0,62,63,
		5,4,0,0,63,64,3,12,6,0,64,65,5,5,0,0,65,66,3,12,6,0,66,87,1,0,0,0,67,68,
		5,9,0,0,68,69,5,50,0,0,69,70,5,26,0,0,70,71,3,6,3,0,71,72,5,22,0,0,72,
		73,3,12,6,0,73,87,1,0,0,0,74,75,5,9,0,0,75,76,5,14,0,0,76,77,5,26,0,0,
		77,78,3,6,3,0,78,79,5,22,0,0,79,80,3,12,6,0,80,87,1,0,0,0,81,82,5,11,0,
		0,82,83,3,12,6,0,83,84,5,12,0,0,84,85,3,12,6,0,85,87,1,0,0,0,86,59,1,0,
		0,0,86,60,1,0,0,0,86,67,1,0,0,0,86,74,1,0,0,0,86,81,1,0,0,0,87,13,1,0,
		0,0,88,89,6,7,-1,0,89,90,3,16,8,0,90,95,1,0,0,0,91,92,10,1,0,0,92,94,3,
		16,8,0,93,91,1,0,0,0,94,97,1,0,0,0,95,93,1,0,0,0,95,96,1,0,0,0,96,15,1,
		0,0,0,97,95,1,0,0,0,98,99,5,33,0,0,99,100,3,12,6,0,100,101,5,38,0,0,101,
		107,1,0,0,0,102,107,5,50,0,0,103,107,5,6,0,0,104,107,5,7,0,0,105,107,5,
		10,0,0,106,98,1,0,0,0,106,102,1,0,0,0,106,103,1,0,0,0,106,104,1,0,0,0,
		106,105,1,0,0,0,107,17,1,0,0,0,108,112,1,0,0,0,109,110,5,28,0,0,110,112,
		3,6,3,0,111,108,1,0,0,0,111,109,1,0,0,0,112,19,1,0,0,0,9,25,32,38,50,57,
		86,95,106,111
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
